"""The libraries the shell's screens read.

Who is signed in, what a screen is, how a settings dialog is laid out, which
columns a list starts with, the appearance a person chose, and the curated icon
set a space may pick from. Shell-only: a bundle without screens has no use for
any of it.
"""

import json
from app_icons import (
    DEFAULT_SPACE_ICON, SPACE_ICON_GROUPS, SPACE_ICONS,
)
from .spec import BANNER


USER_JS = BANNER + """
import { computed } from 'vue'

import { sessionUser } from './boot'
import { useResource } from './resource'

/**
 * The signed-in user.
 *
 * One resource for the whole app: the sidebar, the user menu and anything that
 * greets someone by name all read this rather than each fetching User/me. The
 * desk is not part of the product, so this is the only place anyone sees their
 * own account.
 */
/**
 * Fetched by id, taken from boot.
 *
 * There is no user named 'me': frappe.client.get on it returns 404, whose HTML
 * error page then comes back to be parsed as JSON, and every name and avatar in
 * the app renders from undefined. It failed silently for exactly that reason —
 * the resource is quiet by design, so nothing said so.
 */
export const currentUser = useResource('frappe.client.get', {
  params: { doctype: 'User', name: sessionUser },
  cacheKey: `oneapp-user-${sessionUser}`,
  // A signed-out visitor on the portal has no User doc to read. The option is
  // `immediate`, not `enabled` — useCall ignores anything it does not know, so
  // the wrong name fetches anyway and says nothing.
  immediate: Boolean(sessionUser) && sessionUser !== 'Guest',
  silent: true,
})

export const user = computed(() => currentUser.data || {})
export const fullName = computed(() => user.value.full_name || user.value.name || '')
export const userImage = computed(() => user.value.user_image || '')
export const email = computed(() => user.value.name || '')

/**
 * Sign out, through Frappe rather than around it.
 *
 * A client-side redirect leaves the session cookie valid, so the next request
 * from that browser is still signed in — which is why this is a location change
 * to the framework's own endpoint and not a router push. Three components had
 * their own copy of this line, each with its own copy of this paragraph.
 */
export function signOut() {
  window.location.href = '/api/method/logout'
}
"""


SCREEN_JS = BANNER + """
import { onMounted, onUnmounted, readonly, ref } from 'vue'

/**
 * One breakpoint, shared by both apps.
 *
 * The shell is not responsive CSS — DesktopShell and MobileShell are different
 * components with different slots, so something has to *choose*. Two apps
 * choosing at two widths is how the same account looks like two products on the
 * same tablet.
 *
 * 768px is Tailwind's `md`, so anything that also branches in CSS agrees with
 * this without a second number to keep in step.
 */
const MOBILE_MAX = 767

const mobile = ref(false)
let query = null
let listeners = 0

function apply(event) {
  mobile.value = event.matches
}

export const isMobile = readonly(mobile)

/**
 * Subscribe a component to the breakpoint.
 *
 * Reference-counted around a single MediaQueryList: every shell, header and
 * menu asking the same question shares one listener, and the last one to
 * unmount removes it.
 */
export function useIsMobile() {
  onMounted(() => {
    if (!query) {
      query = window.matchMedia(`(max-width: ${MOBILE_MAX}px)`)
      mobile.value = query.matches
      query.addEventListener('change', apply)
    }
    listeners += 1
  })

  onUnmounted(() => {
    listeners -= 1
    if (listeners <= 0 && query) {
      query.removeEventListener('change', apply)
      query = null
      listeners = 0
    }
  })

  return isMobile
}
"""


SETTINGS_GEOMETRY_JS = """// Generated by scripts/gen_frontend.py. Edit that, not this file.

/**
 * SettingsDialog geometry below frappe-ui's own `sm` breakpoint.
 *
 * frappe-ui 1.0.0-beta.55 makes the dialog full-screen on a phone but keeps the
 * desktop shape inside it: the nav stays a vertical column capped at 38vh — 320
 * pixels of tabs before any content on a tall phone — and every panel pads
 * `px-[4.4rem]`, which leaves 249px of a 390px screen and wraps "API host" one
 * word per line.
 *
 * These reflow it into the shape a phone wants: a horizontally scrolling strip
 * of tabs, then the content. They are fallthrough classes on the library's own
 * components rather than a stylesheet override, so nothing here depends on a
 * class name frappe-ui did not publish, and `max-sm:` is the same breakpoint
 * the dialog switches at — one number, not two that can disagree.
 *
 * `tests/test_settings_dialog_geometry.py` pins the upstream values these
 * compensate for; when frappe-ui makes them responsive, that test fails and
 * this module should go.
 */

/**
 * The nav. Row instead of column, scrolling sideways, uncapped height.
 * `[&>div]` is SettingsSidebar's own `space-y-4` wrapper: laid out as a row it
 * needs the gap on the inline axis and no stacking margin on its children.
 */
export const TAB_STRIP = [
  'max-sm:!max-h-none',
  'max-sm:!flex-row',
  'max-sm:!items-center',
  'max-sm:!gap-2',
  'max-sm:!overflow-x-auto',
  'max-sm:!overflow-y-hidden',
  'max-sm:!p-2',
  'max-sm:[&>div]:flex',
  'max-sm:[&>div]:gap-2',
  'max-sm:[&>div>*]:!mt-0',
].join(' ')

/**
 * A group inside the strip: its heading is a row of its own that a strip has no
 * room for, and its items lay out along the strip rather than down it.
 */
export const TAB_GROUP = [
  'max-sm:[&>div:first-child]:hidden',
  'max-sm:[&>div:last-child]:!flex-row',
  'max-sm:[&>div:last-child]:gap-2',
].join(' ')

/** A tab: as wide as its label, never wrapped, never squeezed. */
export const TAB_ITEM = 'max-sm:!w-auto max-sm:shrink-0 max-sm:whitespace-nowrap'

/** A panel's pinned header. */
export const PANEL_HEADER = 'max-sm:!px-4 max-sm:!pt-5'

/**
 * The panel column, so a wide table scrolls instead of stretching the dialog.
 *
 * A flex item's `min-width` defaults to `auto`: it refuses to shrink below its
 * content. SettingsPanel is a flex item of SettingsContent, so a table
 * declaring `min-w-[40rem]` inside an `overflow-x-auto` wrapper does not make
 * the wrapper scroll — it makes the panel grow. Measured on a Pixel 7, the
 * models panel came out 787px wide in a 412px viewport with a third of it
 * unreachable, and `document.scrollWidth` stayed clean the whole time because
 * the dialog clips what overflows. Every catalogue panel had it.
 *
 * Applied to SettingsContent and reaching its panels, so it is one class in one
 * place rather than a prop every panel has to remember.
 */
export const PANEL_CONTENT = [
  '[&>[role=tabpanel]]:min-w-0',
  // And a *maximum*, which `min-w-0` is not. A panel is a flex item of
  // SettingsContent and is sized by its content, so `min-w-0` only says it may
  // shrink when squeezed — nothing stops it growing past the dialog when its
  // widest row wants more room, and then the dialog clips the right of every
  // line in it, header and all. `w-0` with the flex-grow the panel already has
  // makes the free space the whole of its width, so wide content scrolls.
  '[&>[role=tabpanel]]:w-0',
].join(' ')

/**
 * A panel's scrolling body. The padding lives on the ScrollArea viewport, which
 * SettingsBody hardcodes, so it is reached through the viewport's data-slot
 * rather than by a class on the component.
 */
export const PANEL_BODY = [
  'max-sm:[&_[data-slot=scroll-area-viewport]]:!px-4',
  'max-sm:[&_[data-slot=scroll-area-viewport]]:!pb-6',
].join(' ')

/**
 * A panel's pinned footer — the row Save lives in.
 *
 * SettingsPanel is a flex column of [header, body, footer] and SettingsBody
 * takes `flex-1`, so a sibling placed after it pins to the bottom with no
 * positioning of its own. It has to be there rather than inside the body: a
 * Save button in the scroll region is off-screen on a phone exactly when the
 * form is long enough to need saving. frappe-ui ships SettingsHeader and
 * SettingsBody but no footer, so this is the family's missing third piece.
 */
export const PANEL_FOOTER = [
  'flex shrink-0 items-center gap-2',
  'border-t border-outline-gray-1 bg-surface-elevation-1',
  'px-4 py-3 sm:px-[4.4rem]',
].join(' ')
"""


LIST_COLUMNS_JS = """// Generated by scripts/gen_frontend.py. Edit that, not this file.

import { computed, toValue } from 'vue'
import { useIsMobile } from './screen'

/**
 * A list's grid tracks, narrowed for a phone.
 *
 * frappe-ui's List takes explicit tracks, and fixed rem tracks add up. Three
 * columns sized for a desktop leave about 60px for the identity column on a
 * 390px screen, so the one thing a row exists to name truncates to "W…" while
 * a plan code and a status pill keep their full width. A phone cannot show
 * every column; it has to show the right ones.
 *
 * Declare each column once, with what it does on a phone:
 *
 *   const list = useListColumns([
 *     { key: 'name', header: 'Workspace', track: 'minmax(0,1fr)' },
 *     { key: 'plan', header: 'Plan', track: '10rem', mobile: false },
 *     { key: 'status', header: 'Status', track: '8rem', mobile: '5.5rem' },
 *   ])
 *
 * `mobile: false` drops the column below the breakpoint; a string narrows its
 * track. `shows(key)` is what the matching cell tests, so the tracks and the
 * cells can never disagree about how many columns there are — which renders as
 * every cell in the row shifted one place left.
 */
export function useListColumns(spec) {
  const isMobile = useIsMobile()

  // `toValue` because a column set is not always known at setup. A screen whose
  // columns come from the server — the app host resolves them from the tenant
  // site's own metadata — has to pass a computed, and calling .filter on one
  // throws inside a computed, which renders as a blank page rather than as an
  // error pointing here.
  const declared = computed(() => toValue(spec) || [])

  const visible = computed(() =>
    declared.value.filter((column) => !isMobile.value || column.mobile !== false),
  )

  const columns = computed(() =>
    visible.value.map((column) =>
      isMobile.value && typeof column.mobile === 'string'
        ? column.mobile
        : column.track,
    ),
  )

  const shows = (key) => visible.value.some((column) => column.key === key)

  // Destructure this. Vue unwraps a ref bound at the top level of `setup`, but
  // not one reached through a property, so holding the result as an object and
  // writing `:columns="list.columns"` hands List a ComputedRef — which fails at
  // `columns.join` with a message that names neither the list nor the ref.
  // `tests/test_frontend_guards.py` fails the build on that shape.
  return { visible, columns, shows }
}
"""


APPEARANCE_JS = """// Generated by scripts/gen_frontend.py. Edit that, not this file.

import { computed } from 'vue'
import { useColorScheme } from '@/ui'

/**
 * Light, dark or follow-the-system, in the three shapes the app needs it.
 *
 * Appearance is reachable from the user menu, the phone's More sheet and
 * settings. Three copies of the same list is how one of them ends up missing
 * an option or writing the theme without updating the stored value, so the
 * list and the setter live here and each surface only picks a rendering.
 */
export const SCHEMES = [
  { value: 'light', label: 'Light', icon: 'lucide-sun' },
  { value: 'dark', label: 'Dark', icon: 'lucide-moon' },
  { value: 'system', label: 'System', icon: 'lucide-monitor' },
]

export function useAppearance() {
  const { colorScheme, setColorScheme } = useColorScheme()

  const scheme = computed({
    get: () => colorScheme.value,
    // colorScheme is readonly on purpose: the ref is only a third of the state,
    // alongside the <html> attribute and the stored value. setColorScheme moves
    // all three together.
    set: (value) => setColorScheme(value),
  })

  /** A Dropdown/ContextMenu group — one row per scheme, the current one ticked. */
  const menuGroup = computed(() => ({
    group: 'Appearance',
    options: SCHEMES.map((item) => ({
      label: item.label,
      icon: item.icon,
      selected: colorScheme.value === item.value,
      onClick: () => setColorScheme(item.value),
    })),
  }))

  /** TabButtons options, for a surface with room to show all three at once. */
  const tabOptions = SCHEMES.map((item) => ({
    value: item.value,
    label: item.label,
    iconLeft: item.icon,
  }))

  /** The same three, as icons alone — for a row that already has a word on it. */
  const iconOptions = SCHEMES.map((item) => ({
    value: item.value,
    // `icon` rather than `iconLeft`: TabButtons treats that as an icon-only tab
    // and turns the label into the accessible name.
    icon: item.icon,
    label: item.label,
  }))

  /** Select options, for a settings row. */
  const selectOptions = SCHEMES.map((item) => ({
    value: item.value,
    label: item.label,
  }))

  return { scheme, menuGroup, tabOptions, iconOptions, selectOptions }
}
"""


# The icons an app in the registry may use.
#
# frappe-ui renders `lucide-*` names as Tailwind utility classes, and Tailwind's
# JIT only emits CSS for classes it finds as literal strings in the source. An
# icon typed by an operator and stored in a doctype is in no source file, so it
# emits nothing and the launcher shows an empty box.
#
# Writing the set here is what makes those classes exist in the CSS.
ICONS_JS = """\
/**
 * The icons an app in the registry may use.
 *
 * These literals are what make the CSS exist. frappe-ui renders `lucide-*`
 * names as Tailwind utility classes, and the JIT only emits a class it can find
 * as a literal string — so an icon name that only ever exists in the database
 * renders as an empty box. The icons page gives two ways out: a known set
 * written as literals, or `~icons/lucide/*` imports for a genuinely open one. A
 * registry of apps we define is a known set.
 *
 * Never build an icon class by interpolation; the scanner cannot see it.
 *
 * Generated from scripts/app_icons.py, which also writes the doctype's Select
 * options, so the picker and the stored values cannot drift.
 */

export const SPACE_ICONS = [
{icon_literals}
]

export const DEFAULT_SPACE_ICON = '{default_icon}'

/**
 * The same set, grouped, and with the words each icon answers to.
 *
 * The words were comments in `app_icons.py` before the picker had a search box,
 * which made them exactly as useful as no words at all: nobody looking for the
 * sales app types "chart line". Groups for the same reason — twenty-six glyphs
 * in one grid is a wall, and the same twenty-six under seven headings is a
 * list you can read.
 */
export const SPACE_ICON_GROUPS = {groups}

/** Every icon whose name or words match, in group order. */
export function findSpaceIcons(query) {{
  const text = String(query || '').trim().toLowerCase()
  return SPACE_ICON_GROUPS.map((group) => ({{
    ...group,
    icons: group.icons.filter(
      (one) =>
        !text ||
        one.icon.includes(text) ||
        one.words.some((word) => word.includes(text)),
    ),
  }})).filter((group) => group.icons.length)
}}

/** A name we know renders — for anything stored before the set was narrowed. */
export function spaceIcon(name) {{
  return SPACE_ICONS.includes(name) ? name : DEFAULT_SPACE_ICON
}}
""".format(
    icon_literals="\n".join(f"  '{name}'," for name in SPACE_ICONS),
    default_icon=DEFAULT_SPACE_ICON,
    groups=json.dumps(
        [
            {
                "group": group,
                "icons": [
                    {"icon": icon, "words": list(words)} for icon, words in icons
                ],
            }
            for group, icons in SPACE_ICON_GROUPS
        ],
        indent=2,
    ),
)
