"""What the two SPAs are.

Every other module in this package reads from here: which apps exist, where
each one mounts, which npm versions both are pinned to, and the banner that
marks a file as generated. One definition, so the tenant app and the control
plane cannot disagree about a version or a route.
"""

import os


# The repository root, two levels up: scripts/spa/spec.py -> scripts/ -> here.
ROOT = os.path.join(os.path.dirname(__file__), "..", "..")


# frappe-ui 1.x is Vite 7 / Tailwind 3 / vue-router 4. Pinned in one place so the
# two apps can never disagree about a version.
DEPENDENCIES = {
    "frappe-ui": "^1.0.0-beta.55",
    "socket.io-client": "^4.8.1",
    "vue": "^3.5.13",
    "vue-router": "^4.5.0",
}


DEV_DEPENDENCIES = {
    # The browser pass. Both SPAs get one: the bugs it catches — an empty list,
    # a dialog that will not open, a panel unreachable at one viewport — all
    # render without throwing, so a clean build says nothing about them.
    "@playwright/test": "^1.49.0",
    "@vitejs/plugin-vue": "^6.0.0",
    "autoprefixer": "^10.4.20",
    "eslint": "^9.17.0",
    "eslint-plugin-vue": "^9.32.0",
    # What `no-undef` is told a browser already has. It arrives under eslint
    # anyway, but a rule that fails open — every `window` an error — should not
    # depend on somebody else's dependency tree.
    "globals": "^13.24.0",
    "postcss": "^8.5.0",
    "tailwindcss": "^3.4.17",
    "vite": "^7.0.0",
}


# The repositories and Frappe apps stay oneapp / oneapp_control — renaming those
# would move every import path and every mirror. What customers see is separate,
# and lives here so a rename is one edit rather than a hunt.
#
# One entry, and it used to be two. "OneAdmin" named the operator console at
# `/admin`; the console is a Space inside OneSpace now, so there is no second
# product for a customer or an operator to be looking at, and a constant nothing
# titles is a name waiting to be put back on something by mistake. The control
# plane is `oneapp_control`, which is an app, not a place.
BRAND = {"tenant": "OneSpace"}


APPS = {
    "oneapp": {
        "route": "/one",
        "title": BRAND["tenant"],
        # Two SPAs, two sites, both running at once — see scripts/dev.sh.
        "site": "space.localhost",
        "port": 8001,
        # Doctypes to generate TypeScript definitions for.
        "types": {"oneapp": ["OneSpace Site State"]},
        # The shell family: the rail, the bottom bar, the account menu, the
        # settings dialog. Every signed-in surface either audience has is a
        # Space in here, so this is the only bundle that renders one.
        "shell": True,
    },
    # Signing up, and nothing else.
    #
    # This app served two full SPAs — /admin for operators and /portal for
    # customers. Both are Spaces now, rendered by `oneapp` on this same site,
    # so what is left is the one page somebody reaches *before* they have an
    # account: `/one` sends a Guest to sign in, correctly, and signup cannot.
    #
    # Kept as its own bundle rather than folded into the tenant app because the
    # two answer different questions about who may load them, and a route that
    # is open to Guest should be a small, obvious, separate thing.
    "oneapp_control": {
        "route": "/signup",
        "title": BRAND["tenant"],
        "site": "control.localhost",
        "port": 8000,
        "types": {"oneapp_control": ["Account Request", "Plan", "Region"]},
    },
}


BANNER = "// Generated by scripts/gen_frontend.py. Edit that, not this file.\n"
