"""The two shapes the product is made of: the panel, and the row.

`rounded-6 border border-outline-gray-2 bg-surface-…` appeared in 33 class
lists across 25 files, in thirteen spellings that differed only in ground and
padding. It is the most duplicated markup in the SPA and it is the thing a
reader sees more of than anything else, so every new one was a fresh decision
about a ground and a number — which is how two print previews ended up at two
heights and three floating bars at three elevations.

One component, four decisions, and the two that are not decisions are built
in: the radius is `rounded-6` and the border is a hairline, always. What a
caller chooses is the ground it sits on, how high it floats, how much room is
inside it, and whether it is carrying a warning.

Generated rather than written because the signup page draws panels too, and a
panel that looks different on the way in is the first thing a customer sees.

`tests/test_design_tokens.py::test_the_panel_shape_is_a_component` refuses the
incantation anywhere else.
"""


PANEL_VUE = """<!-- Generated by scripts/gen_frontend.py. Edit that, not this file. -->
<template>
  <component :is="as" data-slot="panel" :class="look">
    <slot />
  </component>
</template>

<script setup>
import { computed } from 'vue'

//: No warning. Named so the template's own comparison is not a bare string.
const NEUTRAL = 'neutral'

// The ground, and the border that goes with it. One map rather than two props,
// because a red panel with a grey border is not a thing anybody wants and
// making it expressible only means somebody eventually writes it.
//
// `base` is the page's own white. `raised` is the surface a shadow is allowed
// to sit on — see the elevation note below, and `lib/shell/theme.js` for why
// dark mode steps *lighter* rather than darker. `sunken` is a well inside a
// panel: a settings group, a read-only preview, the thing that is part of the
// page rather than on top of it.
const GROUND = {
  base: 'border-outline-gray-2 bg-surface-base',
  raised: 'border-outline-gray-2 bg-surface-elevation-2',
  sunken: 'border-outline-gray-2 bg-surface-gray-1',
  amber: 'border-outline-amber-2 bg-surface-amber-1',
  red: 'border-outline-red-2 bg-surface-red-1',
}

// Four rooms and a bar. `bar` is not a smaller `tight`: a row of controls is
// wider than it is tall and wants asymmetric padding, and seven call sites had
// each derived their own version of that — `px-2.5 py-2`, `px-3 py-2.5`,
// `px-4 py-2`, `px-3 py-2`.
const PAD = {
  none: '',
  tight: 'p-3',
  normal: 'p-4',
  loose: 'p-5',
  bar: 'px-3 py-2',
}

// The names from `scripts/spa/build.py`. A panel is the commonest thing that
// floats, so the height is a prop here rather than a class at the call site.
const ELEVATION = {
  flat: '',
  raised: 'shadow-raised',
  floating: 'shadow-floating',
  over: 'shadow-over',
}

const props = defineProps({
  // The literal lists again rather than `value in GROUND`: `defineProps` is
  // hoisted above the component's own scope, so a validator that closes over a
  // local const is a runtime reference error — `vue/valid-define-props` is
  // what catches it, and it caught this.
  ground: {
    type: String,
    default: 'base',
    validator: (value) => ['base', 'raised', 'sunken', 'amber', 'red'].includes(value),
  },
  pad: {
    type: String,
    default: 'normal',
    validator: (value) => ['none', 'tight', 'normal', 'loose', 'bar'].includes(value),
  },
  elevation: {
    type: String,
    default: 'flat',
    validator: (value) => ['flat', 'raised', 'floating', 'over'].includes(value),
  },
  // A warning or a failure, which takes the ground over rather than sitting
  // beside it — an amber panel is amber all the way through.
  tone: {
    type: String,
    default: 'neutral',
    validator: (value) => ['neutral', 'amber', 'red'].includes(value),
  },
  // A panel is sometimes a `<section>`, an `<aside>` or a `<form>`. The
  // default is the one that claims nothing.
  as: { type: String, default: 'div' },
})

// Resolved here rather than in the template, and that is not only tidiness:
// `tests/token_audit.py` reads every string literal inside a `:class`
// expression as a class list, so `tone === 'neutral' ? …` in the markup makes
// `neutral` a utility that emits no CSS and fails the audit. The scan is
// right to be that blunt — a class hidden in an expression is how a retired
// token drew a transparent column for a week.
const look = computed(() => [
  'rounded-6 border',
  GROUND[props.tone === NEUTRAL ? props.ground : props.tone],
  PAD[props.pad],
  ELEVATION[props.elevation],
])
</script>
"""


ROW_STATE_JS = """// Generated by scripts/gen_frontend.py. Edit that, not this file.

/**
 * A row has five states and they must all be legible at once.
 *
 * Before this there was one colour doing three jobs. `bg-surface-gray-2` was
 * the hover, the selected file, the open mail thread, the current version and
 * the open record — so in Drive a hovered file and a selected file were the
 * same colour, in Mail a hovered thread and the open one were, and the only
 * surface that told them apart did it with `aria-current`, which is correct,
 * invisible, and read by nobody using a mouse. The engine's own list rows had
 * no hover at all: the *cell* under the pointer greyed and the row did not,
 * which reads as the cell being the thing you are about to act on when
 * clicking it opens the record. And `focus-visible` appeared once in the
 * whole built stylesheet, so tabbing through a list showed nothing.
 *
 * Five states, five treatments, and the two decisions that make them stack:
 *
 *   rest      the surface
 *   hover     a *lighter* step than selection — it is a pointer, not a choice
 *   focus     a 2px inset ring in the accent, no fill
 *   selected  a fill, plus the tick — it is a set, and a set is counted
 *   open      a 2px leading edge in the accent, and `aria-current` kept
 *
 * **Open is an edge and focus is a ring**, which is the whole of it: a row can
 * be open *and* hovered *and* ticked without three fills fighting over one
 * background. Three fills is why there was only ever one.
 *
 * The accent is the workspace's own — `--surface-gray-10` and
 * `--outline-gray-8` are what `lib/shell/theme.js` paints it into — so the
 * edge that says "you are here" is the same colour as the solid button and
 * the tab indicator, in every workspace.
 *
 * `docs/UNIFICATION.md` §B4.
 */

//: What every interactive row carries. `relative` because the open edge is a
//: pseudo-element pinned to the row's own leading edge, `transition-colors`
//: so the hover arrives rather than snapping, and `group/row` so a cell
//: inside it can show its own affordance on the *row's* hover rather than
//: competing with a fill of its own — which is what an editable cell did, and
//: why the cell under the pointer looked like the thing about to be acted on
//: when clicking it opens the record.
export const ROW = 'group/row relative transition-colors'

//: The pointer is over it. A lighter step than selection on purpose: hover
//: answers "which one am I about to touch", and a hovered row inside a
//: selection must still read as part of the selection.
//:
//: This is the only `hover:bg-` literal in the SPA, and
//: `test_one_hover_fill_and_it_is_here` is what keeps it that way. There were
//: five before — `gray-1`, `gray-2`, `gray-3`, `white/15` and `white/10` —
//: which meant a tile in the space switcher lit up harder than a row in the
//: list beside it for no reason anybody had decided.
export const HOVER = 'hover:bg-surface-gray-1'

/**
 * The same two fills, for a row on a coloured ground.
 *
 * The record showcase paints a record's own image or brand colour behind its
 * children, and a grey fill over a photograph is mud. White alpha is the only
 * hover that works on a ground you do not know — which is the whole reason
 * this is two constants here rather than one class at that call site.
 */
export const HOVER_OVERLAY = 'hover:bg-white/15'
export const SELECTED_OVERLAY = 'bg-white/10'

//: The keyboard is on it. A ring rather than a fill, so it survives on top of
//: hover, selection and open — and inset, so it is not clipped by the
//: scroller a list always sits in.
export const FOCUS =
  'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset ' +
  'focus-visible:ring-outline-gray-8'

//: It is in the set being acted on.
export const SELECTED = 'bg-surface-gray-2'

/**
 * The keyboard is on it, but the keyboard is somewhere else.
 *
 * `FOCUS` only fires on the element that actually holds focus, and in a
 * picker that element is the search box — the caret stays there the whole
 * time somebody is arrowing down the list. So this is the same ring without
 * the pseudo-class, and it is a ring rather than `SELECTED`'s fill for the
 * same reason B4 gave: the row the keyboard is on has not been chosen, and a
 * fill on the first row of an untouched list reads as if it had been.
 */
export const ACTIVE = 'ring-2 ring-inset ring-outline-gray-8'

//: It is the one open in the pane beside the list. An edge rather than a
//: fill; `inset-y-1` so it reads as a mark against the row rather than a
//: border between two of them.
export const OPEN =
  "before:absolute before:inset-y-1 before:start-0 before:w-0.5 " +
  'before:rounded-full before:bg-surface-gray-10'

//: Being dragged: the thing under the pointer, faded where it came from.
export const LIFTED = 'opacity-50'

//: Where it would land. The focus ring's shape in the hairline's colour,
//: because it is a place rather than a state of the thing.
export const DROP = 'ring-2 ring-outline-gray-3'

/**
 * The classes for one row, given what is true about it.
 *
 * A function rather than seven exported strings at every call site, because
 * the order matters — `SELECTED`'s fill has to come before `HOVER`'s so the
 * hover wins on a selected row — and getting that wrong is invisible until
 * somebody hovers a ticked row.
 *
 * `hover` and `focus` default to on and are separate questions, which is the
 * distinction `Row.vue` needed and got wrong twice before it was written
 * down. The focus ring belongs only to something that can hold the keyboard:
 * on a `<li>` it is a promise no tab stop keeps. The hover belongs to almost
 * every row *including* the ones that are only containers for their own
 * controls — a file line with a link and a delete button in it is still one
 * line you are about to act on.
 */
export function rowState({
  selected, active, open, lifted, drop, hover = true, focus = true,
  ground = 'surface',
} = {}) {
  const over = ground === 'overlay'
  return [
    ROW,
    selected ? (over ? SELECTED_OVERLAY : SELECTED) : '',
    hover ? (over ? HOVER_OVERLAY : HOVER) : '',
    focus ? FOCUS : '',
    active ? ACTIVE : '',
    open ? OPEN : '',
    lifted ? LIFTED : '',
    drop ? DROP : '',
  ].filter(Boolean).join(' ')
}

export default {
  ROW, HOVER, HOVER_OVERLAY, FOCUS, ACTIVE, SELECTED, SELECTED_OVERLAY, OPEN,
  LIFTED, DROP, rowState,
}
"""


ROW_VUE = '''<!-- Generated by scripts/gen_frontend.py. Edit that, not this file. -->
<template>
  <component
    :is="element"
    :to="to || undefined"
    :href="href || undefined"
    :type="element === 'button' ? 'button' : undefined"
    :aria-current="open ? 'true' : undefined"
    data-slot="row"
    :class="look"
  >
    <slot v-if="layout === BARE" />
    <template v-else>
      <span v-if="$slots.lead" class="flex shrink-0 items-center">
        <slot name="lead" />
      </span>
      <span class="min-w-0 flex-1"><slot /></span>
      <span v-if="$slots.trail" class="flex shrink-0 items-center gap-1">
        <slot name="trail" />
      </span>
    </template>
  </component>
</template>

<script setup>
import { computed, useAttrs } from 'vue'
import { RouterLink } from 'vue-router'

import { rowState } from '@/lib/rowstate'

//: The escape hatch, named so the template compares against a const rather
//: than a bare string — `tests/token_audit.py` reads every string literal
//: inside a `:class` or a template expression as a class name.
const BARE = 'bare'

// How the row lays itself out, and there are only two because there were only
// ever two shapes under the seventeen hand-rolled ones.
//
// `row` is fifteen of them: something at the start, something in the middle
// that is allowed to run out of room, something at the end. `bare` is the
// other two — Mail's thread, which is two stacked lines each with their own
// start and end, and anything else that is genuinely not a line. `bare`
// contributes no layout at all, so the caller's own `flex flex-col` cannot
// lose a fight with the component's `items-center`, which is what a third
// layout prop would have guaranteed.
const LAYOUT = {
  row: 'flex w-full gap-3 text-start',
  bare: 'w-full text-start',
}

//: Where the lead and the trail sit against a body that wrapped. `start` is
//: for the rows whose body is two or three lines — a notification, a finding.
const ALIGN = { center: 'items-center', start: 'items-start' }

// Three rooms, down from the seven spellings the call sites had between them
// (`px-2 py-1.5`, `px-2.5 py-2`, `px-3 py-2`, `px-3 py-2.5`, `px-4 py-2`,
// `px-4 py-2.5`, `px-4 py-3`). The two-pixel differences were nobody's
// decision; they are what happens when each surface picks its own.
const PAD = {
  none: '',
  tight: 'px-2 py-1.5',
  normal: 'px-3 py-2.5',
  loose: 'px-4 py-3',
}

// What separates one row from the next, and it is one question with three
// answers rather than two independent props. A list either rules between its
// rows or floats them apart; doing both is how a settings list ended up with
// a hairline *and* a gap, which reads as two lists.
const EDGE = {
  divider: 'border-b border-outline-gray-1 last:border-0',
  // The row is its own tile. The gap comes from the parent's `gap-*`, because
  // the parent is the only thing that knows how many there are.
  rounded: 'rounded-4',
  none: '',
}

const props = defineProps({
  // Where it goes. A row that is a place is a link — that is what makes the
  // back button work and a reload land in the same row — so `to` is the first
  // thing to reach for and `@click` is for rows that do something instead.
  to: { type: [String, Object], default: null },
  href: { type: String, default: '' },
  //: Overrides the element entirely, for the caller that needs an `<li>`.
  as: { type: [String, Object], default: null },

  // The five states, straight through to `rowState`. `selected` is the set
  // being acted on, `open` is the one in the pane beside the list, and the
  // last two are the drag.
  selected: { type: Boolean, default: false },
  //: The keyboard is on it while the caret is elsewhere — a picker's list.
  active: { type: Boolean, default: false },
  open: { type: Boolean, default: false },
  lifted: { type: Boolean, default: false },
  drop: { type: Boolean, default: false },

  // Literal arrays rather than `value in PAD`: `defineProps` is hoisted above
  // the component's scope, so a validator closing over a local const is a
  // reference error at runtime. Panel.vue learned this first.
  layout: {
    type: String,
    default: 'row',
    validator: (value) => ['row', 'bare'].includes(value),
  },
  align: {
    type: String,
    default: 'center',
    validator: (value) => ['center', 'start'].includes(value),
  },
  pad: {
    type: String,
    default: 'normal',
    validator: (value) => ['none', 'tight', 'normal', 'loose'].includes(value),
  },
  edge: {
    type: String,
    default: 'divider',
    validator: (value) => ['divider', 'rounded', 'none'].includes(value),
  },

  //: A row that is decoration rather than a line in a list — a header, a
  //: total. Off is rare enough to be the thing you say.
  hover: { type: Boolean, default: true },

  //: What is behind it. `overlay` is a row over a photograph or a brand
  //: colour, where a grey fill is mud — see `lib/rowstate.js`.
  ground: {
    type: String,
    default: 'surface',
    validator: (value) => ['surface', 'overlay'].includes(value),
  },
})

const attrs = useAttrs()

/**
 * What element this actually is, worked out rather than asked for.
 *
 * A row that navigates is a link, a row that acts is a button, and a row that
 * does neither is a `div` — and getting that wrong is not cosmetic: the
 * hand-rolled ones included clickable `<div>`s, which the keyboard cannot
 * reach and a screen reader does not announce. Deriving it means no caller
 * can get it wrong by forgetting.
 */
const element = computed(() => {
  if (props.as) return props.as
  if (props.to) return RouterLink
  if (props.href) return 'a'
  return attrs.onClick ? 'button' : 'div'
})

/**
 * Whether the row itself can hold the keyboard — which is not the same
 * question as whether it reacts to a pointer, and conflating the two is how
 * this was got wrong twice.
 *
 * The focus ring belongs only to a row that can actually be focused: drawn on
 * a `<li>` it is a promise no tab stop keeps. The *hover* belongs to almost
 * every row, including the ones that are containers for their own controls —
 * a file line with a link and a delete button in it is still one line you are
 * about to act on, and highlighting it is what makes a column of forty
 * scannable. So hover is a prop with a default and focus is derived.
 */
const interactive = computed(() => Boolean(props.to || props.href || attrs.onClick))

const look = computed(() => [
  rowState({
    selected: props.selected,
    active: props.active,
    open: props.open,
    lifted: props.lifted,
    drop: props.drop,
    hover: props.hover,
    focus: interactive.value,
    ground: props.ground,
  }),
  LAYOUT[props.layout],
  props.layout === BARE ? '' : ALIGN[props.align],
  PAD[props.pad],
  EDGE[props.edge],
])
</script>
'''
