"""The two shapes the product is made of: the panel, and the row.

`rounded-6 border border-outline-gray-2 bg-surface-…` appeared in 33 class
lists across 25 files, in thirteen spellings that differed only in ground and
padding. It is the most duplicated markup in the SPA and it is the thing a
reader sees more of than anything else, so every new one was a fresh decision
about a ground and a number — which is how two print previews ended up at two
heights and three floating bars at three elevations.

One component, four decisions, and the two that are not decisions are built
in: the radius is `rounded-6` and the border is a hairline, always. What a
caller chooses is the ground it sits on, how high it floats, how much room is
inside it, and whether it is carrying a warning.

Generated rather than written because the signup page draws panels too, and a
panel that looks different on the way in is the first thing a customer sees.

`tests/test_design_tokens.py::test_the_panel_shape_is_a_component` refuses the
incantation anywhere else.
"""


PANEL_VUE = """<!-- Generated by scripts/gen_frontend.py. Edit that, not this file. -->
<template>
  <component :is="as" data-slot="panel" :class="look">
    <slot />
  </component>
</template>

<script setup>
import { computed } from 'vue'

//: No warning. Named so the template's own comparison is not a bare string.
const NEUTRAL = 'neutral'

// The ground, and the border that goes with it. One map rather than two props,
// because a red panel with a grey border is not a thing anybody wants and
// making it expressible only means somebody eventually writes it.
//
// `base` is the page's own white. `raised` is the surface a shadow is allowed
// to sit on — see the elevation note below, and `lib/shell/theme.js` for why
// dark mode steps *lighter* rather than darker. `sunken` is a well inside a
// panel: a settings group, a read-only preview, the thing that is part of the
// page rather than on top of it.
const GROUND = {
  base: 'border-outline-gray-2 bg-surface-base',
  raised: 'border-outline-gray-2 bg-surface-elevation-2',
  sunken: 'border-outline-gray-2 bg-surface-gray-1',
  amber: 'border-outline-amber-2 bg-surface-amber-1',
  red: 'border-outline-red-2 bg-surface-red-1',
}

// Four rooms and a bar. `bar` is not a smaller `tight`: a row of controls is
// wider than it is tall and wants asymmetric padding, and seven call sites had
// each derived their own version of that — `px-2.5 py-2`, `px-3 py-2.5`,
// `px-4 py-2`, `px-3 py-2`.
const PAD = {
  none: '',
  tight: 'p-3',
  normal: 'p-4',
  loose: 'p-5',
  bar: 'px-3 py-2',
}

// The names from `scripts/spa/build.py`. A panel is the commonest thing that
// floats, so the height is a prop here rather than a class at the call site.
const ELEVATION = {
  flat: '',
  raised: 'shadow-raised',
  floating: 'shadow-floating',
  over: 'shadow-over',
}

const props = defineProps({
  // The literal lists again rather than `value in GROUND`: `defineProps` is
  // hoisted above the component's own scope, so a validator that closes over a
  // local const is a runtime reference error — `vue/valid-define-props` is
  // what catches it, and it caught this.
  ground: {
    type: String,
    default: 'base',
    validator: (value) => ['base', 'raised', 'sunken', 'amber', 'red'].includes(value),
  },
  pad: {
    type: String,
    default: 'normal',
    validator: (value) => ['none', 'tight', 'normal', 'loose', 'bar'].includes(value),
  },
  elevation: {
    type: String,
    default: 'flat',
    validator: (value) => ['flat', 'raised', 'floating', 'over'].includes(value),
  },
  // A warning or a failure, which takes the ground over rather than sitting
  // beside it — an amber panel is amber all the way through.
  tone: {
    type: String,
    default: 'neutral',
    validator: (value) => ['neutral', 'amber', 'red'].includes(value),
  },
  // A panel is sometimes a `<section>`, an `<aside>` or a `<form>`. The
  // default is the one that claims nothing.
  as: { type: String, default: 'div' },
})

// Resolved here rather than in the template, and that is not only tidiness:
// `tests/token_audit.py` reads every string literal inside a `:class`
// expression as a class list, so `tone === 'neutral' ? …` in the markup makes
// `neutral` a utility that emits no CSS and fails the audit. The scan is
// right to be that blunt — a class hidden in an expression is how a retired
// token drew a transparent column for a week.
const look = computed(() => [
  'rounded-6 border',
  GROUND[props.tone === NEUTRAL ? props.ground : props.tone],
  PAD[props.pad],
  ELEVATION[props.elevation],
])
</script>
"""


ROW_STATE_JS = """// Generated by scripts/gen_frontend.py. Edit that, not this file.

/**
 * A row has five states and they must all be legible at once.
 *
 * Before this there was one colour doing three jobs. `bg-surface-gray-2` was
 * the hover, the selected file, the open mail thread, the current version and
 * the open record — so in Drive a hovered file and a selected file were the
 * same colour, in Mail a hovered thread and the open one were, and the only
 * surface that told them apart did it with `aria-current`, which is correct,
 * invisible, and read by nobody using a mouse. The engine's own list rows had
 * no hover at all: the *cell* under the pointer greyed and the row did not,
 * which reads as the cell being the thing you are about to act on when
 * clicking it opens the record. And `focus-visible` appeared once in the
 * whole built stylesheet, so tabbing through a list showed nothing.
 *
 * Five states, five treatments, and the two decisions that make them stack:
 *
 *   rest      the surface
 *   hover     a *lighter* step than selection — it is a pointer, not a choice
 *   focus     a 2px inset ring in the accent, no fill
 *   selected  a fill, plus the tick — it is a set, and a set is counted
 *   open      a 2px leading edge in the accent, and `aria-current` kept
 *
 * **Open is an edge and focus is a ring**, which is the whole of it: a row can
 * be open *and* hovered *and* ticked without three fills fighting over one
 * background. Three fills is why there was only ever one.
 *
 * The accent is the workspace's own — `--surface-gray-10` and
 * `--outline-gray-8` are what `lib/shell/theme.js` paints it into — so the
 * edge that says "you are here" is the same colour as the solid button and
 * the tab indicator, in every workspace.
 *
 * `docs/UNIFICATION.md` §B4.
 */

//: What every interactive row carries. `relative` because the open edge is a
//: pseudo-element pinned to the row's own leading edge, `transition-colors`
//: so the hover arrives rather than snapping, and `group/row` so a cell
//: inside it can show its own affordance on the *row's* hover rather than
//: competing with a fill of its own — which is what an editable cell did, and
//: why the cell under the pointer looked like the thing about to be acted on
//: when clicking it opens the record.
export const ROW = 'group/row relative transition-colors'

//: The pointer is over it. A lighter step than selection on purpose: hover
//: answers "which one am I about to touch", and a hovered row inside a
//: selection must still read as part of the selection.
export const HOVER = 'hover:bg-surface-gray-1'

//: The keyboard is on it. A ring rather than a fill, so it survives on top of
//: hover, selection and open — and inset, so it is not clipped by the
//: scroller a list always sits in.
export const FOCUS =
  'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset ' +
  'focus-visible:ring-outline-gray-8'

//: It is in the set being acted on.
export const SELECTED = 'bg-surface-gray-2'

//: It is the one open in the pane beside the list. An edge rather than a
//: fill; `inset-y-1` so it reads as a mark against the row rather than a
//: border between two of them.
export const OPEN =
  "before:absolute before:inset-y-1 before:start-0 before:w-0.5 " +
  'before:rounded-full before:bg-surface-gray-10'

//: Being dragged: the thing under the pointer, faded where it came from.
export const LIFTED = 'opacity-50'

//: Where it would land. The focus ring's shape in the hairline's colour,
//: because it is a place rather than a state of the thing.
export const DROP = 'ring-2 ring-outline-gray-3'

/**
 * The classes for one row, given what is true about it.
 *
 * A function rather than five exported strings at every call site, because
 * the order matters — `SELECTED`'s fill has to come before `HOVER`'s so the
 * hover wins on a selected row — and getting that wrong is invisible until
 * somebody hovers a ticked row.
 */
export function rowState({ selected, open, lifted, drop } = {}) {
  return [
    ROW,
    selected ? SELECTED : '',
    HOVER,
    FOCUS,
    open ? OPEN : '',
    lifted ? LIFTED : '',
    drop ? DROP : '',
  ].filter(Boolean).join(' ')
}

export default { ROW, HOVER, FOCUS, SELECTED, OPEN, LIFTED, DROP, rowState }
"""
