"""Write every doctype JSON in both apps, from one declaration each.

A doctype hand-edited in the desk and a doctype in this repository are two
different things, and only one of them survives a fresh site. So the JSONs are
generated: `scripts/doctypes/` declares them, this file writes them, and
`tests/test_generated_doctypes.py` fails if a file on disk is not what running
this produces.

It also writes the two modules that follow from the same declarations — the
fieldtype map the SPA reads, and the AI capability list — so those cannot drift
from the Select options that describe them either.

Names are re-exported here because `gen.DOCTYPES` and `gen.APPS` are how the
guards have always reached them.

Run: python3 scripts/gen_doctypes.py
"""

import json
import os

from doctypes import (
    APPS, APPS_ROOT, DOCTYPES, HANDLED_SPEC_KEYS, MANAGER_PERMS,
    READONLY_PERMS, STAMP,
)


def build(spec):
    fields = spec["fields"]
    doc = {
        "actions": [],
        "allow_rename": spec.get("allow_rename", 1),
        "creation": STAMP,
        "doctype": "DocType",
        "editable_grid": 1,
        "engine": "InnoDB",
        "field_order": [x["fieldname"] for x in fields],
        "fields": fields,
        "index_web_pages_for_search": 1,
        "links": [],
        "modified": STAMP,
        "modified_by": "Administrator",
        "module": APPS[spec["app"]][2],
        "name": spec["name"],
        "owner": "Administrator",
        "permissions": spec["perms"],
        "sort_field": "modified",
        "sort_order": "DESC",
        # Frappe's Document States: one colour per value of the field a screen
        # calls its status. The desk reads these for its indicators and so does
        # `spaceview.presentation`, so a status is one colour in the list, in
        # the record header and in the desk alike.
        #
        # Empty for a doctype no screen shows a badge for. Where a screen *does*
        # declare a `status_field`, `test_manifests.py` insists every option of
        # it is here — because the alternative is not "no colour", it is
        # `valueTheme`'s word list guessing from the text. "Failed" happens to
        # come out red and "Draining" happens to come out gray, and neither is
        # a decision anybody made.
        "states": [
            {"title": title, "color": color} for title, color in spec.get("states", ())
        ],
        # On by default: a Version row per edit is what makes an operator's
        # change to a plan or a shard answerable. Off only for a document that
        # is written by machinery rather than by a person — a cache rewritten on
        # every sync would file a Version every few minutes, for a change nobody
        # made and nobody would ever read.
        "track_changes": spec.get("track_changes", 1),
    }
    if spec.get("in_create"):
        # Frappe's own "User Cannot Create". It does *not* remove the create
        # permission — `has_permission(create)` stays true, which is what lets
        # the code that owns these keep writing them — it tells a UI not to
        # offer New. Frappe's desk reads it in `perm.js` and `toolbar.js`;
        # OneSpace reads it in `spaceview._resolve`.
        doc["in_create"] = 1
    if spec.get("autoname"):
        doc["autoname"] = spec["autoname"]
    if spec.get("title_field"):
        doc["title_field"] = spec["title_field"]
        doc["show_title_field_in_link"] = 1

    if spec.get("search_fields"):
        # What a picker searches besides the id and the title, and what it
        # prints under each result. Frappe's own desk reads it the same way —
        # "Contact" without "the one at Halloway" is not a choice anybody can
        # make, and until now every link target of ours answered with the id
        # alone and nothing underneath it.
        doc["search_fields"] = spec["search_fields"]
    if spec.get("issingle"):
        doc["issingle"] = 1
        doc.pop("allow_rename", None)

    if spec.get("istable"):
        # A child table is not a doctype with a parent field bolted on: without
        # this Frappe builds an ordinary table with no parent/parenttype/idx
        # columns, and every read through the parent fails with
        # "Unknown column 'parent' in 'WHERE'".
        doc["istable"] = 1
        doc["editable_grid"] = 1
        doc.pop("allow_rename", None)
        doc["permissions"] = []

    # Anything in the spec this function does not know about was silently
    # dropped before now — istable was, and the doctype generated as a normal
    # table that nothing could read. Fail instead.
    unknown = set(spec) - HANDLED_SPEC_KEYS
    if unknown:
        raise SystemExit(f"{spec['name']}: build() ignores {sorted(unknown)}")

    return doc


CONTROLLER = '''import frappe
from frappe.model.document import Document


class {cls}(Document):
\tpass
'''


CAPABILITIES_MODULE = '''"""Capabilities, and the provider task names that map onto them.

Generated by scripts/gen_doctypes.py from scripts/ai_capabilities.py. Do not
edit: the same list fills the AI Model and AI Feature Selects, and a second
hand-maintained copy is how a model ends up in a bucket the settings page does
not offer.
"""

CAPABILITIES = {caps}

CAPABILITY_NAMES = list(CAPABILITIES)


def for_task(task: str) -> str | None:
	"""The capability a provider's task name means, or None if we do not know.

	None is a real answer. A model whose task we cannot place is left for review
	rather than filed under the nearest-looking capability, because the cost of
	guessing is a feature calling a model that cannot do the job.
	"""
	if not task:
		return None

	needle = task.strip().lower()
	for capability, aliases in CAPABILITIES.items():
		if needle == capability.lower() or needle in aliases:
			return capability
	return None
'''


FIELDTYPES_MODULE = '''"""Every Frappe fieldtype, and whether we offer to write it.

Generated by scripts/gen_doctypes.py from scripts/field_types.py. Do not edit:
the browser reads the same table out of `src/lib/fields.js`, and the one thing
worse than the two disagreeing is them disagreeing about `editable` — the form
would offer a control the server then refuses.
"""

# fieldtype -> (control, cell, icon, editable)
FIELD_TYPES = {fields}

LAYOUT_TYPES = {layout}

DATA_OPTIONS = {data_options}

# Frappe's own bookkeeping. Never a column, never a control: a customer editing
# `owner` or `docstatus` is always a mistake.
RESERVED = {reserved}


def editable(fieldtype: str) -> bool:
	"""Whether a field of this type can be offered for editing at all.

	Unknown is not editable. If we do not know what it is, we do not know how to
	write it, and a text box over an unknown type saves the wrong shape.
	"""
	row = FIELD_TYPES.get(fieldtype)
	return bool(row and row[3])


def icon_for(fieldtype: str) -> str:
	return (FIELD_TYPES.get(fieldtype) or (None, None, "lucide-circle-help", False))[2]


def cell_for(fieldtype: str) -> str:
	return (FIELD_TYPES.get(fieldtype) or (None, "text", None, False))[1]


def is_layout(fieldtype: str) -> bool:
	"""A section break, a column break, a heading. Carries no value, so it is
	never a column and never something to filter."""
	return fieldtype in LAYOUT_TYPES


# --------------------------------------------------------------------------- #
# Filter operators, ported from Frappe's own filter UI and inverted from its
# per-fieldtype deny list into an allow list. `tests/test_field_types.py` reads
# `filter.js` back and fails when the two disagree.
# --------------------------------------------------------------------------- #

# operator -> label, in the order Frappe lists them.
OPERATORS = {operators}

# Frappe relabels the comparisons for a date: "Before" reads better than "<".
OPERATOR_LABELS_BY_TYPE = {operator_labels}

# operator -> whether a fieldtype may use it.
VALID_OPERATORS = {valid_operators}

# Frappe's relative-date vocabulary. Handed to its `timespan` operator verbatim,
# so a value it does not know is a filter that returns nothing and says nothing.
TIMESPANS = {timespans}

DEFAULT_OPERATORS = {default_operators}

_EQUALITY = ("=", "!=")
_IN = ("in", "not in")


def operators_for(fieldtype: str) -> tuple:
	"""Which operators a filter on this fieldtype may use.

	A fieldtype nobody listed gets equality and `is`. An allow list rather than
	Frappe's deny list precisely so that is the answer: on a server, a fieldtype
	nobody thought about must not inherit every operator.
	"""
	return VALID_OPERATORS.get(fieldtype, ("=", "!=", "is"))


def default_operator(fieldtype: str, fieldname: str = "") -> str:
	"""What a filter opens on. A Data field is almost always a substring
	search, a date almost always a range."""
	if fieldname in ("_assign", "_liked_by"):
		# Stored as a JSON array, so an exact match can never hit.
		return "like"
	return DEFAULT_OPERATORS.get(fieldtype, "=")


def value_shape(fieldtype: str, operator: str) -> str:
	"""What the value has to be, once the operator is known.

	Frappe does this by rewriting the docfield in `set_fieldtype`; the same
	decision, named, so the server can check a value without rendering one.
	"""
	if operator == "is":
		return "set"
	if operator == "timespan":
		return "timespan"
	if operator == "between":
		return "range"
	if operator in _IN:
		return "multi"
	if fieldtype in ("Check", "Select"):
		return "choice"
	if fieldtype in ("Link", "Dynamic Link") and operator in _EQUALITY:
		return "link"
	# Everything else is a plain box, a Link under `like` included: matching
	# part of a name is a text question.
	return "value"
'''


def write_fieldtypes():
    """Emit the fieldtype table into the tenant app."""
    import pprint
    import sys as _sys

    _sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    import field_types
    from field_types import DATA_OPTIONS, FIELD_TYPES, LAYOUT_TYPES

    reserved = (
        "doctype", "name", "owner", "creation", "modified", "modified_by",
        "docstatus", "idx", "parent", "parenttype", "parentfield",
        "_user_tags", "_comments", "_assign", "_liked_by", "_seen",
        "naming_series",
    )

    valid = {t: field_types.operators_for(t) for t in FIELD_TYPES}
    defaults = {t: field_types.default_operator(t) for t in FIELD_TYPES}

    body = FIELDTYPES_MODULE.format(
        fields=pprint.pformat(FIELD_TYPES, width=92, sort_dicts=True),
        layout=pprint.pformat(LAYOUT_TYPES, width=88),
        data_options=pprint.pformat(DATA_OPTIONS, width=88, sort_dicts=True),
        reserved=pprint.pformat(frozenset(reserved), width=88),
        operators=pprint.pformat(field_types.OPERATORS, width=88, sort_dicts=False),
        operator_labels=pprint.pformat(
            field_types.OPERATOR_LABELS_BY_TYPE, width=88, sort_dicts=False),
        valid_operators=pprint.pformat(valid, width=92, sort_dicts=True),
        timespans=pprint.pformat(dict(field_types.TIMESPANS), width=88, sort_dicts=False),
        default_operators=pprint.pformat(defaults, width=88, sort_dicts=True),
    )
    path = os.path.join(APPS_ROOT, "oneapp", "oneapp", "oneapp_core")
    with open(os.path.join(path, "fieldtypes.py"), "w") as fh:
        fh.write(body)


def write_capabilities():
    """Emit the capability map into the control plane app."""
    import pprint

    from ai_capabilities import CAPABILITIES

    body = CAPABILITIES_MODULE.format(caps=pprint.pformat(CAPABILITIES, width=88))
    path = os.path.join(APPS_ROOT, "oneapp_control", "oneapp_control", "ai")
    os.makedirs(path, exist_ok=True)
    open(os.path.join(path, "__init__.py"), "a").close()
    with open(os.path.join(path, "capabilities.py"), "w") as fh:
        fh.write(body)


def main():
    write_capabilities()
    write_fieldtypes()
    written = []
    for name, spec in DOCTYPES.items():
        pkg, module_dir, _ = APPS[spec["app"]]
        base = os.path.join(APPS_ROOT, pkg, pkg, module_dir, "doctype")
        # Frappe's own `scrub`: spaces and hyphens both become underscores, so
        # "Add-on" is looked for at add_on/add_on.json. Getting this wrong
        # produces a directory Frappe never reads and a doctype that silently
        # does not exist.
        slug = name.lower().replace(" ", "_").replace("-", "_")
        d = os.path.join(base, slug)
        os.makedirs(d, exist_ok=True)
        open(os.path.join(d, "__init__.py"), "a").close()
        with open(os.path.join(d, f"{slug}.json"), "w") as fh:
            json.dump(build(spec), fh, indent=1, sort_keys=True)
            fh.write("\n")
        ctrl = os.path.join(d, f"{slug}.py")
        if not os.path.exists(ctrl):
            # The class name Frappe looks for is the doctype with spaces and
            # hyphens removed — `base_document.get_controller` builds it that
            # way, so "Add-on" is `Addon` and anything else is an ImportError at
            # the first read.
            cls = name.replace(" ", "").replace("-", "")
            with open(ctrl, "w") as fh:
                fh.write(CONTROLLER.format(cls=cls))
        written.append(name)
    print(f"{len(written)} doctypes: " + ", ".join(sorted(written)))


if __name__ == "__main__":
    main()
