"""Generate the frontend setup for every SPA in the monorepo.

Two SPAs — the tenant app and the admin control plane — must look and behave
like one product. The risk is drift: two Vite configs, two Tailwind setups, two
different ideas of which components are allowed, diverging a little at a time.

They cannot share an npm workspace, because each app is mirrored to its own
repository for Frappe Cloud and has to be self-contained. So the shared setup is
*generated* into both instead, from the single definition below, exactly as the
doctypes are. `scripts/check_frontend.py` fails CI if either copy is edited by
hand.

Everything here follows frappe-ui's own conventions rather than reimplementing
them: `frappe-ui/vite` owns the dev proxy, build paths and index.html;
`frappe-ui/tailwind` owns the design tokens.

Run: python3 scripts/gen_frontend.py
"""

import json
import os

from app_icons import APP_ICONS, DEFAULT_APP_ICON

ROOT = os.path.join(os.path.dirname(__file__), "..")

# frappe-ui 1.x is Vite 7 / Tailwind 3 / vue-router 4. Pinned in one place so the
# two apps can never disagree about a version.
DEPENDENCIES = {
    "frappe-ui": "^1.0.0-beta.55",
    "socket.io-client": "^4.8.1",
    "vue": "^3.5.13",
    "vue-router": "^4.5.0",
}

DEV_DEPENDENCIES = {
    "@vitejs/plugin-vue": "^6.0.0",
    "autoprefixer": "^10.4.20",
    "eslint": "^9.17.0",
    "eslint-plugin-vue": "^9.32.0",
    "postcss": "^8.5.0",
    "tailwindcss": "^3.4.17",
    "vite": "^7.0.0",
}

# The repositories and Frappe apps stay oneapp / oneapp_control — renaming those
# would move every import path and every mirror. What customers see is separate,
# and lives here so a rename is one edit rather than a hunt.
BRAND = {"tenant": "OneSpace", "admin": "OneAdmin"}

APPS = {
    "oneapp": {
        "route": "/one",
        "title": BRAND["tenant"],
        # Doctypes to generate TypeScript definitions for.
        "types": {"oneapp": ["OneApp Site State"]},
    },
    "oneapp_control": {
        "route": "/admin",
        "title": BRAND["admin"],
        # Extra Frappe routes serving the same bundle. One build, several
        # server-side guards: /admin is System Managers only, /portal has to let
        # a signed-out visitor reach signup. Sharing the bundle is what keeps
        # the two surfaces from drifting into separate frontends.
        "shells": [{"name": "portal", "title": BRAND["tenant"]}],
        "types": {
            "oneapp_control": [
                "Tenant", "Shard", "Plan", "Subscription",
                "Provisioning Job", "Credit Ledger Entry", "OneApp App",
            ]
        },
    },
}

BANNER = "// Generated by scripts/gen_frontend.py. Edit that, not this file.\n"


def vite_config(app: str, spec: dict) -> str:
    types = json.dumps(spec["types"], indent=2).replace('"', "'")
    html_name = spec["route"].lstrip("/")
    shells = json.dumps(spec.get("shells", []))
    return BANNER + f"""
import {{ defineConfig }} from 'vite'
import vue from '@vitejs/plugin-vue'
import frappeui from 'frappe-ui/vite'
import fs from 'node:fs'
import path from 'node:path'

// Frappe serves one .html per website route. frappe-ui's plugin emits exactly
// one, so the additional surfaces are copies of it — same hashed asset tags,
// different <title>, and a sibling .py that decides who may load them. Copying
// after the build is what guarantees they can never reference stale assets.
const EXTRA_SHELLS = {shells}

function extraShells() {{
  return {{
    name: 'oneapp-extra-shells',
    closeBundle() {{
      if (!EXTRA_SHELLS.length) return
      const source = path.resolve(__dirname, '../{app}/www/{html_name}.html')
      if (!fs.existsSync(source)) {{
        // Silently skipping would ship a route that 404s with nothing to
        // explain why, so fail the build instead.
        throw new Error(`extraShells: ${{source}} was not emitted by frappe-ui`)
      }}
      const html = fs.readFileSync(source, 'utf8')
      for (const shell of EXTRA_SHELLS) {{
        fs.writeFileSync(
          path.resolve(__dirname, `../{app}/www/${{shell.name}}.html`),
          html.replace(/<title>[^<]*<\\/title>/, `<title>${{shell.title}}</title>`),
        )
      }}
    }},
  }}
}}

// frappe-ui's plugin owns the parts that are easy to get subtly wrong: it
// proxies /api, /app, /assets, /files and /private to the bench it detects from
// common_site_config.json, and it emits ../{app}/www/<route>.html so the SPA is
// served by Frappe itself. Hand-rolling any of that is how the two apps drift.
export default defineConfig({{
  plugins: [
    frappeui({{
      frontendRoute: '{spec["route"]}',
      // Given explicitly rather than inferred. frappe-ui derives these by
      // walking up for a bench layout (a directory with both sites/ and apps/),
      // which exists on Frappe Cloud but not in this monorepo — so inference
      // returns null here and the production build fails with
      // "indexHtmlPath is required". Stating them makes the build identical
      // everywhere: monorepo, bench, and CI.
      buildConfig: {{
        outDir: path.resolve(__dirname, '../{app}/public/frontend'),
        indexHtmlPath: '../{app}/www/{html_name}.html',
      }},
      frappeTypes: {{
        input: {types},
      }},
    }}),
    vue(),
    extraShells(),
  ],
  resolve: {{
    alias: {{ '@': path.resolve(__dirname, 'src') }},
  }},
}})
"""


def index_html(app: str, spec: dict) -> str:
    """Vite's entry document.

    The frappe-ui plugin transforms this into ../<app>/www/<route>.html at build
    time — it does not create it, so this file has to exist.

    The inline theme script runs before first paint. Without it the page flashes
    white before Tailwind loads, because `bg-surface-base` only resolves once the
    stylesheet arrives.
    """
    return f"""<!doctype html>
<html class="h-full" lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover" />
    <title>{spec["title"]}</title>
    <script>
      ;(function () {{
        try {{
          var stored = localStorage.getItem('theme')
          var theme = stored === 'light' || stored === 'dark' ? stored : null
          if (!theme) {{
            theme = window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light'
          }}
          document.documentElement.setAttribute('data-theme', theme)
          document.documentElement.style.backgroundColor =
            theme === 'dark' ? '#171717' : '#ffffff'
        }} catch (e) {{}}
      }})()
    </script>
    <link rel="icon" type="image/svg+xml" href="/assets/{app}/favicon.svg" />
    <meta name="theme-color" media="(prefers-color-scheme: light)" content="#ffffff" />
    <meta name="theme-color" media="(prefers-color-scheme: dark)" content="#171717" />
  </head>
  <body class="h-full bg-surface-base">
    <div id="app" class="h-full"></div>
    <script type="module" src="/src/main.js"></script>
  </body>
</html>
"""


def tailwind_config(app: str) -> str:
    return BANNER + """
import preset, { content as frappeUIContent } from 'frappe-ui/tailwind'

// Tailwind 3 does not merge `content` from a preset, so frappe-ui's own source
// globs have to be listed here or half the component styles are purged out.
export default {
  presets: [preset],
  content: [...frappeUIContent, './index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
}
"""


def postcss_config(app: str) -> str:
    return BANNER + """
export default {
  plugins: { tailwindcss: {}, autoprefixer: {} },
}
"""


def app_root_package_json(app: str, spec: dict) -> str:
    """Repo-root package.json.

    Frappe Cloud installs and builds an app by running yarn at its repository
    root, so this is what makes the SPA exist in a deployed bench at all.
    Without it the build silently does nothing and the www page 404s, because
    the HTML is emitted by the Vite build rather than committed.
    """
    return json.dumps(
        {
            "name": app.replace("_", "-"),
            "private": True,
            "type": "module",
            "_generated": "scripts/gen_frontend.py",
            "scripts": {
                "postinstall": "cd frontend && yarn install",
                "dev": "cd frontend && yarn dev",
                "build": "cd frontend && yarn build",
                "lint": "cd frontend && yarn lint",
            },
        },
        indent=2,
    ) + "\n"


def package_json(app: str, spec: dict) -> str:
    return json.dumps(
        {
            "name": f"{app.replace('_', '-')}-frontend",
            "private": True,
            "type": "module",
            "version": "0.0.1",
            "_generated": "scripts/gen_frontend.py",
            "scripts": {
                "dev": "vite",
                "build": "vite build",
                "preview": "vite preview",
                "lint": "eslint src",
            },
            "dependencies": DEPENDENCIES,
            "devDependencies": DEV_DEPENDENCIES,
        },
        indent=2,
    ) + "\n"


def eslint_config(app: str) -> str:
    return BANNER + """
import pluginVue from 'eslint-plugin-vue'

// The guard. Every native control here has a frappe-ui equivalent, and using the
// raw element is how a design system quietly stops being one — a plain <button>
// looks close enough in isolation and wrong next to everything else.
//
// Escape hatch is a one-line eslint-disable with a reason, so bypassing it is a
// visible decision rather than an accident.
const BANNED = [
  { element: 'button', message: 'Use <Button> from @/ui instead of a raw <button>.' },
  { element: 'input', message: 'Use <TextInput>, <FormControl>, <Checkbox> or <Switch> from @/ui.' },
  { element: 'select', message: 'Use <Select> or <Autocomplete> from @/ui.' },
  { element: 'textarea', message: 'Use <Textarea> or <FormControl type="textarea"> from @/ui.' },
  { element: 'dialog', message: 'Use <Dialog> from @/ui.' },
  { element: 'table', message: 'Use <ListView> from frappe-ui/list.' },
]

export default [
  ...pluginVue.configs['flat/recommended'],
  {
    files: ['src/**/*.vue'],
    rules: {
      'vue/no-restricted-html-elements': ['error', ...BANNED],
      'vue/multi-word-component-names': 'off',
      'vue/no-v-html': 'error',

      // Formatting is a formatter's job. Left on, these produce dozens of
      // warnings per file and train everyone to ignore lint output — which is
      // where the rules that actually matter live.
      'vue/max-attributes-per-line': 'off',
      'vue/singleline-html-element-content-newline': 'off',
      'vue/html-self-closing': 'off',
      'vue/html-indent': 'off',
      'vue/html-closing-bracket-newline': 'off',
      'vue/attributes-order': 'off',
      'vue/first-attribute-linebreak': 'off',
    },
  },
  {
    // The shared runtime is exempt — it is what wraps frappe-ui.
    files: ['src/**/*.{js,vue}'],
    ignores: ['src/ui.js', 'src/lib/**'],
    rules: {
      'no-restricted-imports': ['error', {
        paths: [
          {
            name: 'frappe-ui',
            // Two separate reasons, both load-bearing:
            //  - components: '@/ui' is the one reviewable list of what is allowed
            //  - data/notify: '@/lib/resource' and '@/lib/notify' are what apply
            //    response unwrapping, Frappe error parsing, toasts and sound
            message:
              "Import components from '@/ui', data helpers from '@/lib/resource', " +
              "and toasts from '@/lib/notify'. Going direct skips error parsing, " +
              'response unwrapping and notification sound.',
          },
          {
            name: 'frappe-ui/list',
            message: \"Import list components from '@/ui' too — one import path \" +
              'for the whole sanctioned surface.',
          },
          {
            name: 'socket.io-client',
            message: "Use onDoctypeChange from '@/lib/socket' — one shared, " +
              'reference-counted socket per app.',
          },
        ],
      }],
      // console.error is deliberate in the error normaliser; noise elsewhere.
      'no-console': ['warn', { allow: ['warn', 'error'] }],
    },
  },
  {
    // The layout primitives belong to AppShell and nothing else.
    //
    // DesktopShell and MobileShell are different components with different
    // slots, so every surface that composes them directly makes its own choice
    // about the breakpoint, about whether a rail appears, and about how a phone
    // reaches the app switcher. Two surfaces choosing differently is how one
    // account starts looking like two products on the same tablet — and the
    // mobile shell has no rail slot at all, so 'just use MobileShell' silently
    // drops app switching.
    files: ['src/**/*.vue'],
    ignores: ['src/components/AppShell.vue'],
    rules: {
      'no-restricted-imports': ['error', {
        paths: [{
          name: '@/ui',
          importNames: [
            'DesktopShell', 'MobileShell', 'MobileNav', 'MobileNavItem',
            'Rail', 'RailItem',
          ],
          message:
            'Compose <AppShell> instead. It owns the desktop/mobile split, the ' +
            'rail, and the bottom-bar app switcher, so every surface agrees.',
        }],
      }],
    },
  },
]
"""


# Components the design system sanctions. Adding one here is the deliberate act
# that makes it available to both apps at once.
UI_BARREL = BANNER + """
/**
 * The sanctioned frappe-ui surface.
 *
 * Both SPAs import from here rather than from 'frappe-ui' directly, so what the
 * product may use is one reviewable list instead of whatever each file reached
 * for. ESLint enforces it, and a test asserts this covers everything frappe-ui
 * exports — a component missing here is a component someone will hand-roll.
 *
 * Reach for a component before writing markup. A <div> with divide-y is not a
 * list; a <router-link> with an active class is not a sidebar item. They look
 * close in isolation and wrong beside everything else.
 */

export {
  // ----- Shell -----------------------------------------------------------
  // DesktopShell renders a PageHeaderTarget and a ScrollArea itself, so pages
  // teleport their header up with <PageHeader> rather than laying one out.
  DesktopShell,
  MobileShell,
  MobileNav,
  MobileNavItem,
  Rail,
  RailItem,
  ScrollArea,
  ScrollBar,

  // ----- Page header -----------------------------------------------------
  PageHeader,
  PageHeaderBase,
  PageHeaderTitle,
  PageHeaderBackButton,
  PageHeaderMobile,
  PageHeaderMobileTitle,
  PageHeaderTarget,

  // ----- Sidebar ---------------------------------------------------------
  Sidebar,
  SidebarItem,
  SidebarLabel,
  SidebarSection,
  SidebarHeader,
  SidebarCard,
  SidebarCollapseToggle,

  // ----- Settings --------------------------------------------------------
  // A whole family, so settings surfaces are composed rather than hand-built.
  SettingsDialog,
  SettingsSidebar,
  SettingsNavGroup,
  SettingsNavItem,
  SettingsBody,
  SettingsContent,
  SettingsPanel,
  SettingsHeader,
  SettingsRow,

  // ----- Structure -------------------------------------------------------
  Divider,
  Breadcrumbs,
  Tabs,
  TabList,
  TabTrigger,
  TabPanel,
  TabButtons,

  // ----- Actions ---------------------------------------------------------
  Button,
  Dropdown,
  ContextMenu,

  // ----- Form controls ---------------------------------------------------
  FormControl,
  FormLabel,
  TextInput,
  Textarea,
  Password,
  Select,
  Combobox,
  MultiSelect,
  Checkbox,
  Switch,
  Radio,
  RadioGroup,
  Slider,
  Rating,
  DatePicker,
  DateTimePicker,
  DateRangePicker,
  TimePicker,
  Duration,
  FileUploader,
  ErrorMessage,

  // ----- Feedback --------------------------------------------------------
  Alert,
  Badge,
  Progress,
  Spinner,
  LoadingIndicator,
  LoadingText,
  Skeleton,
  Tooltip,
  TooltipProvider,

  // ----- Overlays --------------------------------------------------------
  Dialog,
  Popover,
  HoverCard,
  BottomSheet,
  KeyboardShortcut,
  KeyboardShortcutsDialog,

  // ----- Display ---------------------------------------------------------
  Avatar,
  Icon,
  Tree,
  ItemListRow,

  // ----- Root provider ---------------------------------------------------
  FrappeUIProvider,

  // ----- Imperative ------------------------------------------------------
  toast,
  dialog,

  // ----- Composables -----------------------------------------------------
  usePageMeta,
  useColorScheme,
  useKeyboardShortcut,
  useShellScrolled,
  useFileUpload,

  // ----- Directives ------------------------------------------------------
  vFocus,
  vOnOutsideClick,

  // ----- Data and utilities ----------------------------------------------
  call,
  frappeRequest,
  setConfig,
  getConfig,
  upload,
  dayjs,
  dayjsLocal,
  debounce,
} from 'frappe-ui'

/**
 * The list family. A separate entry point in frappe-ui because it ships its own
 * structural CSS; re-exported here so pages have one import path.
 *
 * `List` takes grid track sizes via `columns` and handles dividers, selection
 * and the active row. Reach for it before writing a table or a stack of divs.
 */
export {
  List,
  ListHeader,
  ListHeaderCell,
  ListHeaderCellSort,
  ListRows,
  ListRow,
  ListCell,
  ListGroup,
} from 'frappe-ui/list'
"""



# --------------------------------------------------------------------------- #
# Shared runtime
#
# Data fetching, realtime, error rendering and notifications are identical in
# both SPAs by construction. Written once here, generated into both, and
# enforced by ESLint so no page can quietly bypass them.
# --------------------------------------------------------------------------- #

BOOT_JS = BANNER + """
/**
 * Boot data injected by frappe-ui's vite plugin.
 *
 * The plugin's jinjaBootData sub-plugin writes the www page's `boot` context
 * onto `window`, so whatever the page controller puts there is available before
 * the app mounts. Everything here degrades to a sane default, because the dev
 * server serves index.html without Jinja and would otherwise crash on boot.
 */

// The plugin emits `window["<key>"] = <value>` for each key in the page's boot
// context — so `boot.site_name` lands as `window.site_name`, not under a `boot`
// object. Reading window.boot would silently yield undefined and leave the
// socket pointed at the wrong host.
const read = (key, fallback) => (window[key] !== undefined ? window[key] : fallback)

export const siteName = read('site_name', window.location.hostname)
export const socketioPort = read('socketio_port', 9000)
export const csrfToken = read('csrf_token', null)
export const sessionUser = read('user', 'Guest')
// Frappe stores datetimes in the system timezone, not the reader's. `dayjsLocal`
// converts between the two, but only once it has been told which system zone to
// convert from — see main.js. Empty is the safe default: dayjsLocal then behaves
// exactly like dayjs rather than shifting by a guess.
export const systemTimezone = read('system_timezone', '')
export const isDev = import.meta.env.DEV

export default { siteName, socketioPort, csrfToken, sessionUser, systemTimezone, isDev }
"""


ERRORS_JS = BANNER + """
/**
 * Frappe error normalisation.
 *
 * Frappe reports failures in several shapes: a FrappeResponseError from
 * frappe-ui's fetch layer, a JSON body with `_server_messages` (itself a
 * JSON-encoded array of JSON-encoded objects), an `exception` traceback string,
 * or a bare Error. Rendering any of those raw gives users a stack trace or
 * "[object Object]".
 *
 * This flattens all of them to { title, message, detail }, where `message` is
 * safe to show and `detail` is for the console.
 */

/** Strip the HTML Frappe puts in server messages. */
function stripTags(value) {
  if (typeof value !== 'string') return value
  const el = document.createElement('div')
  el.innerHTML = value
  return (el.textContent || '').trim()
}

/** `_server_messages` is a JSON string containing JSON strings. */
function parseServerMessages(raw) {
  if (!raw) return []
  try {
    const outer = typeof raw === 'string' ? JSON.parse(raw) : raw
    return (Array.isArray(outer) ? outer : [outer])
      .map((entry) => {
        try {
          return typeof entry === 'string' ? JSON.parse(entry) : entry
        } catch {
          return { message: entry }
        }
      })
      .filter(Boolean)
  } catch {
    return []
  }
}

/** Last frame of a traceback is the only useful line for a user-facing hint. */
function lastTracebackLine(exception) {
  if (typeof exception !== 'string') return ''
  const lines = exception.trim().split('\\n').filter(Boolean)
  return lines.length ? lines[lines.length - 1].trim() : ''
}

export function normalizeError(error) {
  if (!error) return { title: 'Something went wrong', message: '', detail: null }

  const messages = parseServerMessages(
    error.messages || error._server_messages || error.response?._server_messages,
  )

  const first = messages[0] || {}
  const fromServer = stripTags(first.message)

  // FrappeResponseError already carries the parsed fields.
  const title =
    first.title ||
    error.title ||
    (error.name === 'FrappeResponseError' ? 'Request failed' : null) ||
    'Something went wrong'

  const message =
    fromServer ||
    stripTags(error.message) ||
    lastTracebackLine(error.exception) ||
    'No further detail was returned.'

  return {
    title: stripTags(title),
    message,
    // Extra server messages beyond the first, shown as additional lines.
    extra: messages.slice(1).map((m) => stripTags(m.message)).filter(Boolean),
    indicator: first.indicator || error.indicator || 'red',
    detail: error.exception || error.stack || null,
    raw: error,
  }
}

export function errorText(error) {
  const { title, message } = normalizeError(error)
  return message && message !== title ? `${title}: ${message}` : title
}
"""


SOUND_JS = BANNER + """
/**
 * Notification sounds.
 *
 * Synthesised with WebAudio rather than shipped as audio files: two short tones
 * need no network request, no asset pipeline, and no licensing.
 *
 * Browsers refuse to start an AudioContext before a user gesture, so the
 * context is created lazily on first play and every failure is swallowed — a
 * silent notification is fine, a thrown error inside a toast is not.
 */

const STORAGE_KEY = 'oneapp:sound'

let context = null

function audioContext() {
  if (context) return context
  const Ctor = window.AudioContext || window.webkitAudioContext
  if (!Ctor) return null
  try {
    context = new Ctor()
  } catch {
    context = null
  }
  return context
}

export function soundEnabled() {
  try {
    return localStorage.getItem(STORAGE_KEY) !== 'off'
  } catch {
    // Private mode and blocked storage both throw; default to on.
    return true
  }
}

export function setSoundEnabled(enabled) {
  try {
    localStorage.setItem(STORAGE_KEY, enabled ? 'on' : 'off')
  } catch {
    /* nothing we can do, and nothing worth failing for */
  }
}

/** Two notes: rising for success, falling for failure. */
const TONES = {
  success: [660, 880],
  error: [440, 330],
}

function playTone(frequencies) {
  const ctx = audioContext()
  if (!ctx) return

  // Autoplay policy may leave it suspended until a gesture.
  if (ctx.state === 'suspended') ctx.resume().catch(() => {})

  const now = ctx.currentTime
  frequencies.forEach((frequency, index) => {
    const start = now + index * 0.09
    const osc = ctx.createOscillator()
    const gain = ctx.createGain()

    osc.type = 'sine'
    osc.frequency.value = frequency

    // Short envelope; a click is what you get without the ramps.
    gain.gain.setValueAtTime(0, start)
    gain.gain.linearRampToValueAtTime(0.05, start + 0.01)
    gain.gain.exponentialRampToValueAtTime(0.0001, start + 0.16)

    osc.connect(gain).connect(ctx.destination)
    osc.start(start)
    osc.stop(start + 0.18)
  })
}

export function playSound(kind) {
  if (!soundEnabled()) return
  try {
    playTone(TONES[kind] || TONES.success)
  } catch {
    /* audio is a nicety; never let it break a notification */
  }
}
"""


NOTIFY_JS = BANNER + """
/**
 * Notifications.
 *
 * Every mutation reports its outcome and every failure is rendered from a
 * normalised Frappe error, so users never see a raw traceback or a silent
 * no-op. Both play a short tone.
 *
 * Pages should not call `toast` directly — these wrappers are what guarantee
 * the sound and the error parsing happen.
 */

import { toast } from 'frappe-ui'

import { normalizeError } from './errors'
import { playSound } from './sound'

export function notifySuccess(message, options = {}) {
  playSound('success')
  return toast.success(message, options)
}

export function notifyError(error, options = {}) {
  const { title, message, extra, detail } = normalizeError(error)

  // The traceback goes to the console, never the toast.
  if (detail) console.error(title, detail)

  playSound('error')
  return toast.error(title, {
    description: [message, ...(extra || [])].filter(Boolean).join('\\n'),
    duration: 8000,
    ...options,
  })
}

export function notifyInfo(message, options = {}) {
  return toast.info(message, options)
}

export { toast }
"""


SOCKET_JS = BANNER + """
/**
 * Frappe realtime.
 *
 * Frappe's socket.io server namespaces connections by site and pushes a
 * `list_update` event whenever a document changes. Subscribing to the doctypes
 * a page renders keeps it fresh without polling.
 *
 * One socket per app, shared by every subscriber. Subscriptions are reference
 * counted so a component unmounting does not cut off another that still needs
 * the same doctype.
 */

import { io } from 'socket.io-client'
import { onScopeDispose, getCurrentScope } from 'vue'

import { siteName, socketioPort, isDev } from './boot'

let socket = null
const subscribers = new Map()

function socketUrl() {
  // In development Vite serves the SPA, so the socket has to be addressed
  // directly on the bench's socketio port. In production it is proxied on the
  // site's own origin.
  if (isDev) {
    return `${window.location.protocol}//${window.location.hostname}:${socketioPort}/${siteName}`
  }
  return `${window.location.origin}/${siteName}`
}

export function getSocket() {
  if (socket) return socket

  socket = io(socketUrl(), {
    withCredentials: true,
    reconnection: true,
    reconnectionAttempts: Infinity,
    // Back off rather than hammering a bench that is restarting.
    reconnectionDelay: 1000,
    reconnectionDelayMax: 10000,
  })

  socket.on('connect', () => {
    // Re-subscribe after a reconnect; the server forgets on disconnect.
    for (const doctype of subscribers.keys()) {
      socket.emit('doctype_subscribe', doctype)
    }
  })

  socket.on('list_update', (data) => {
    const handlers = subscribers.get(data?.doctype)
    if (handlers) handlers.forEach((fn) => fn(data.name, data))
  })

  return socket
}

/**
 * Call `handler` whenever any document of `doctype` changes.
 * Returns an unsubscribe function, and cleans up automatically inside a
 * component scope.
 */
export function onDoctypeChange(doctype, handler) {
  const sock = getSocket()

  if (!subscribers.has(doctype)) {
    subscribers.set(doctype, new Set())
    sock.emit('doctype_subscribe', doctype)
  }
  subscribers.get(doctype).add(handler)

  const stop = () => {
    const handlers = subscribers.get(doctype)
    if (!handlers) return
    handlers.delete(handler)
    if (handlers.size === 0) {
      subscribers.delete(doctype)
      sock.emit('doctype_unsubscribe', doctype)
    }
  }

  if (getCurrentScope()) onScopeDispose(stop)
  return stop
}

export function closeSocket() {
  if (!socket) return
  socket.close()
  socket = null
  subscribers.clear()
}
"""


RESOURCE_JS = BANNER + """
/**
 * The single way this app talks to Frappe.
 *
 * Wraps frappe-ui's useCall so that every request in both SPAs gets the same
 * treatment:
 *
 *   - responses unwrapped, so pages read `data` rather than `data.message`
 *   - failures rendered through the Frappe error normaliser and toasted
 *   - mutations announce their result
 *   - lists refresh over the socket instead of polling
 *
 * ESLint forbids importing useCall or call directly, so this cannot be bypassed
 * without a visible disable comment.
 */

import { watch } from 'vue'
import {
  useCall,
  useList,
  useDoc,
  useDoctype,
  call as rawCall,
  frappeRequest,
} from 'frappe-ui'

import { notifyError, notifySuccess } from './notify'
import { onDoctypeChange } from './socket'

/**
 * Unwrap Frappe's envelope.
 *
 * Depending on the endpoint a response arrives as the value, as `{message: …}`,
 * or occasionally as `{message: {message: …}}` when a whitelisted method
 * returns something already enveloped. Pages should never have to care.
 */
export function normalize(data) {
  let value = data
  let depth = 0

  while (
    value &&
    typeof value === 'object' &&
    !Array.isArray(value) &&
    'message' in value &&
    Object.keys(value).length === 1 &&
    depth < 3
  ) {
    value = value.message
    depth += 1
  }

  return value
}

/**
 * A read. Toasts on failure; silent on success.
 *
 * `watch` names doctypes whose changes should trigger a refetch over the
 * socket.
 */
/**
 * Where useCall's reads have to point, and why it is v2.
 *
 * Two separate traps, and both end in a page that renders nothing:
 *
 * 1. useCall concatenates `url` onto the base without adding a prefix, so a
 *    bare dotted method resolves *relative to the current page*. Under our SPA
 *    route rules Frappe answers that with the app's own HTML at 200, so the
 *    fetch fails parsing JSON rather than 404ing.
 *
 * 2. useCall reads its payload as `data.value?.data` — the API **v2** envelope.
 *    `/api/method/…` is v1 and answers `{message: …}`, so the lookup finds
 *    nothing and the resource settles with `data === null` after a perfectly
 *    successful request. Every `useResource` read was silently empty: the
 *    customer portal sat on its spinner and the user menu showed "Account"
 *    instead of a name.
 *
 * `/api/v2/method/…` returns `{data: …}`, which is what useCall is built to
 * read. `normalize()` below stays as the belt to this braces — a whitelisted
 * method that returns something already enveloped still unwraps correctly.
 */
function methodUrl(method) {
  if (method.startsWith('/') || method.startsWith('http')) return method
  return `/api/v2/method/${method}`
}

export function useResource(url, options = {}) {
  const { watch: watchDoctypes = [], silent = false, transform, onError, ...rest } = options

  const resource = useCall({
    url: methodUrl(url),
    transform: (data) => {
      const value = normalize(data)
      return transform ? transform(value) : value
    },
    onError: (error) => {
      if (!silent) notifyError(error)
      onError?.(error)
    },
    ...rest,
  })

  for (const doctype of watchDoctypes) {
    onDoctypeChange(doctype, () => resource.reload())
  }

  return resource
}

/**
 * A write. Always announces its outcome — a save that appears to do nothing is
 * indistinguishable from a broken one.
 */
export function useAction(url, options = {}) {
  const {
    successMessage = 'Saved',
    silent = false,
    transform,
    onSuccess,
    onError,
    ...rest
  } = options

  return useCall({
    url,
    method: 'POST',
    immediate: false,
    transform: (data) => {
      const value = normalize(data)
      return transform ? transform(value) : value
    },
    onSuccess: (data) => {
      if (!silent && successMessage) notifySuccess(successMessage)
      onSuccess?.(data)
    },
    onError: (error) => {
      if (!silent) notifyError(error)
      onError?.(error)
    },
    ...rest,
  })
}

/**
 * Documents and lists, through frappe-ui's own document layer.
 *
 * `useList` / `useDoc` / `useDoctype` are the recommended layer for new code —
 * they share one document store, so a row updated through a list and the same
 * document opened on a detail page stay in step, and they carry pagination and
 * write helpers. Rolling our own on top of `frappe.client.get_list` gave up all
 * of that and shadowed the library's name while doing it.
 *
 * These wrappers exist for the same reason `useResource` does: to apply one
 * error policy, and to refetch over the socket rather than by polling.
 */
export function useDocList(doctype, options = {}) {
  const { watch: watchDoctypes = [doctype], silent = false, onError, ...rest } = options

  const list = useList({
    doctype,
    onError: (error) => {
      if (!silent) notifyError(error)
      onError?.(error)
    },
    ...rest,
  })

  for (const watched of watchDoctypes) {
    onDoctypeChange(watched, () => list.reload())
  }

  return list
}

/**
 * One document. `name` may be a getter, so a detail page can follow its route
 * parameter without a watcher of its own.
 *
 * useDoc reports failures through its `error` ref rather than an `onError`
 * option, so the toast is wired to that.
 */
export function useDocument(doctype, name, options = {}) {
  const { watch: watchDoctypes = [doctype], silent = false, ...rest } = options

  const resource = useDoc({ doctype, name, ...rest })

  if (!silent) {
    watch(
      () => resource.error,
      (error) => error && notifyError(error),
    )
  }

  for (const watched of watchDoctypes) {
    onDoctypeChange(watched, () => resource.reload())
  }

  return resource
}

/**
 * The write side of a doctype — insert, setValue, delete, runDocMethod.
 *
 * Every submit runs independently, so saving two records at once does not
 * cancel either. `frappe.client.set_value` through `callMethod` was one shared
 * request that did.
 */
export function useDocWrites(doctype, options = {}) {
  const { successMessage, silent = false } = options
  const writes = useDoctype(doctype)

  const announce = (fn) => async (...args) => {
    try {
      const result = await fn(...args)
      if (successMessage && !silent) notifySuccess(successMessage)
      return result
    } catch (error) {
      if (!silent) notifyError(error)
      throw error
    }
  }

  return {
    raw: writes,
    insert: announce((values) => writes.insert.submit(values)),
    setValue: announce((values) => writes.setValue.submit(values)),
    delete: announce((name) => writes.delete.submit({ name })),
  }
}

/**
 * One-off call for imperative code. Normalised and toasted like everything else.
 *
 * `method: 'GET'` for reads. frappe-ui's `call()` is POST-only, and a method
 * whitelisted `methods=["GET"]` rejects a POST as a PermissionError — which
 * reads like an auth problem and is not one. That is what made every read on
 * the signup page fail, so the page reported signups closed on a site where
 * they were open. `tests/test_api_calls.py` checks the verb against the
 * whitelist now.
 */
export async function callMethod(method, params = {}, options = {}) {
  const { successMessage, silent = false, method: verb = 'POST' } = options
  try {
    const response =
      verb === 'POST'
        ? await rawCall(method, params)
        : await frappeRequest({ url: method, method: verb, params })
    const data = normalize(response)
    if (successMessage && !silent) notifySuccess(successMessage)
    return data
  } catch (error) {
    if (!silent) notifyError(error)
    throw error
  }
}
"""


# --------------------------------------------------------------------------- #
# Shared components
#
# Surfaces both SPAs need identically. Generated rather than duplicated so the
# account menu, the empty state and the theme control cannot drift into two
# slightly different things.
# --------------------------------------------------------------------------- #

USER_JS = BANNER + """
import { computed } from 'vue'

import { sessionUser } from './boot'
import { useResource } from './resource'

/**
 * The signed-in user.
 *
 * One resource for the whole app: the sidebar, the user menu and anything that
 * greets someone by name all read this rather than each fetching User/me. The
 * desk is not part of the product, so this is the only place anyone sees their
 * own account.
 */
/**
 * Fetched by id, taken from boot.
 *
 * There is no user named 'me': frappe.client.get on it returns 404, whose HTML
 * error page then comes back to be parsed as JSON, and every name and avatar in
 * the app renders from undefined. It failed silently for exactly that reason —
 * the resource is quiet by design, so nothing said so.
 */
export const currentUser = useResource('frappe.client.get', {
  params: { doctype: 'User', name: sessionUser },
  cacheKey: `oneapp-user-${sessionUser}`,
  // A signed-out visitor on the portal has no User doc to read. The option is
  // `immediate`, not `enabled` — useCall ignores anything it does not know, so
  // the wrong name fetches anyway and says nothing.
  immediate: Boolean(sessionUser) && sessionUser !== 'Guest',
  silent: true,
})

export const user = computed(() => currentUser.data || {})
export const fullName = computed(() => user.value.full_name || user.value.name || '')
export const userImage = computed(() => user.value.user_image || '')
export const email = computed(() => user.value.name || '')
"""

BRAND_JS = BANNER + """
/**
 * What customers call us.
 *
 * The repositories and Frappe apps are oneapp and oneapp_control; those names
 * are internal and stay put. Nothing user-visible should spell either of them,
 * so every surface reads these instead.
 */
export const TENANT_APP = 'OneSpace'
export const ADMIN_APP = 'OneAdmin'
"""

SCREEN_JS = BANNER + """
import { onMounted, onUnmounted, readonly, ref } from 'vue'

/**
 * One breakpoint, shared by both apps.
 *
 * The shell is not responsive CSS — DesktopShell and MobileShell are different
 * components with different slots, so something has to *choose*. Two apps
 * choosing at two widths is how the same account looks like two products on the
 * same tablet.
 *
 * 768px is Tailwind's `md`, so anything that also branches in CSS agrees with
 * this without a second number to keep in step.
 */
const MOBILE_MAX = 767

const mobile = ref(false)
let query = null
let listeners = 0

function apply(event) {
  mobile.value = event.matches
}

export const isMobile = readonly(mobile)

/**
 * Subscribe a component to the breakpoint.
 *
 * Reference-counted around a single MediaQueryList: every shell, header and
 * menu asking the same question shares one listener, and the last one to
 * unmount removes it.
 */
export function useIsMobile() {
  onMounted(() => {
    if (!query) {
      query = window.matchMedia(`(max-width: ${MOBILE_MAX}px)`)
      mobile.value = query.matches
      query.addEventListener('change', apply)
    }
    listeners += 1
  })

  onUnmounted(() => {
    listeners -= 1
    if (listeners <= 0 && query) {
      query.removeEventListener('change', apply)
      query = null
      listeners = 0
    }
  })

  return isMobile
}
"""


LIST_COLUMNS_JS = """// Generated by scripts/gen_frontend.py. Edit that, not this file.

import { computed } from 'vue'
import { useIsMobile } from './screen'

/**
 * A list's grid tracks, narrowed for a phone.
 *
 * frappe-ui's List takes explicit tracks, and fixed rem tracks add up. Three
 * columns sized for a desktop leave about 60px for the identity column on a
 * 390px screen, so the one thing a row exists to name truncates to "W…" while
 * a plan code and a status pill keep their full width. A phone cannot show
 * every column; it has to show the right ones.
 *
 * Declare each column once, with what it does on a phone:
 *
 *   const list = useListColumns([
 *     { key: 'name', header: 'Workspace', track: 'minmax(0,1fr)' },
 *     { key: 'plan', header: 'Plan', track: '10rem', mobile: false },
 *     { key: 'status', header: 'Status', track: '8rem', mobile: '5.5rem' },
 *   ])
 *
 * `mobile: false` drops the column below the breakpoint; a string narrows its
 * track. `shows(key)` is what the matching cell tests, so the tracks and the
 * cells can never disagree about how many columns there are — which renders as
 * every cell in the row shifted one place left.
 */
export function useListColumns(spec) {
  const isMobile = useIsMobile()

  const visible = computed(() =>
    spec.filter((column) => !isMobile.value || column.mobile !== false),
  )

  const columns = computed(() =>
    visible.value.map((column) =>
      isMobile.value && typeof column.mobile === 'string'
        ? column.mobile
        : column.track,
    ),
  )

  const shows = (key) => visible.value.some((column) => column.key === key)

  // Destructure this. Vue unwraps a ref bound at the top level of `setup`, but
  // not one reached through a property, so holding the result as an object and
  // writing `:columns="list.columns"` hands List a ComputedRef — which fails at
  // `columns.join` with a message that names neither the list nor the ref.
  // `tests/test_frontend_guards.py` fails the build on that shape.
  return { visible, columns, shows }
}
"""


APPEARANCE_JS = """// Generated by scripts/gen_frontend.py. Edit that, not this file.

import { computed } from 'vue'
import { useColorScheme } from '@/ui'

/**
 * Light, dark or follow-the-system, in the three shapes the app needs it.
 *
 * Appearance is reachable from the user menu, the phone's More sheet and
 * settings. Three copies of the same list is how one of them ends up missing
 * an option or writing the theme without updating the stored value, so the
 * list and the setter live here and each surface only picks a rendering.
 */
export const SCHEMES = [
  { value: 'light', label: 'Light', icon: 'lucide-sun' },
  { value: 'dark', label: 'Dark', icon: 'lucide-moon' },
  { value: 'system', label: 'System', icon: 'lucide-monitor' },
]

export function useAppearance() {
  const { colorScheme, setColorScheme } = useColorScheme()

  const scheme = computed({
    get: () => colorScheme.value,
    // colorScheme is readonly on purpose: the ref is only a third of the state,
    // alongside the <html> attribute and the stored value. setColorScheme moves
    // all three together.
    set: (value) => setColorScheme(value),
  })

  /** A Dropdown/ContextMenu group — one row per scheme, the current one ticked. */
  const menuGroup = computed(() => ({
    group: 'Appearance',
    options: SCHEMES.map((item) => ({
      label: item.label,
      icon: item.icon,
      selected: colorScheme.value === item.value,
      onClick: () => setColorScheme(item.value),
    })),
  }))

  /** TabButtons options, for a surface with room to show all three at once. */
  const tabOptions = SCHEMES.map((item) => ({
    value: item.value,
    label: item.label,
    iconLeft: item.icon,
  }))

  /** Select options, for a settings row. */
  const selectOptions = SCHEMES.map((item) => ({
    value: item.value,
    label: item.label,
  }))

  return { scheme, menuGroup, tabOptions, selectOptions }
}
"""


APP_SHELL_VUE = """<!-- Generated by scripts/gen_frontend.py. Edit that, not this file. -->
<template>
  <!--
    Mobile navigation, and what decides what goes where.

    MobileNav is a grid: every item takes an equal share of the bar, so five is
    the practical ceiling before the labels stop being readable on a 360px
    phone. A sidebar can hold twenty entries; a bottom bar cannot, and picking
    the first twenty is not a design.

    So the last slot is always the same thing — the account avatar, opening a
    sheet — and the four before it are the app's primary destinations. Anything
    a surface declares past the fourth, or marks `primary: false`, falls into
    that sheet rather than being dropped. The sheet is also the only place a
    phone can reach what the desktop keeps in the rail footer and the sidebar
    foot: the app switcher, settings, appearance, the account itself.

    This mirrors frappe-ui's own MobileNav example, whose last item is a "You"
    avatar rather than another destination.
  -->
  <MobileShell v-if="isMobile">
    <slot />

    <template #nav>
      <MobileNav>
        <MobileNavItem
          v-for="item in primaryNav"
          :key="item.label"
          :label="item.label"
          :icon="item.icon"
          :to="item.to"
          :active="item.active"
        >
          <!-- The default slot replaces the icon, not the label, so a badged
               item still reads the same as its neighbours. -->
          <template v-if="item.badge" #default="{ active }">
            <span class="relative">
              <Icon
                :name="item.icon"
                class="size-6"
                :class="active ? 'text-ink-gray-8' : 'text-ink-gray-5'"
              />
              <Badge
                class="absolute -right-2.5 -top-1 scale-90"
                :theme="item.badge.theme"
                :label="item.badge.label"
                variant="subtle"
              />
            </span>
          </template>
        </MobileNavItem>

        <MobileNavItem label="More" :active="showMenu" @click="showMenu = true">
          <template #default="{ active }">
            <Avatar
              :label="user.name || user.email || 'Account'"
              :image="user.avatar"
              size="md"
              :class="active ? 'ring-2 ring-outline-gray-4' : ''"
            />
          </template>
        </MobileNavItem>
      </MobileNav>
    </template>
  </MobileShell>

  <DesktopShell v-else :scroll="scroll">
    <template v-if="apps.length" #rail>
      <Rail class="border-r border-outline-gray-1">
        <RailItem
          v-for="app in apps"
          :key="app.key"
          :label="app.label"
          :description="app.description"
          :active="app.key === activeApp"
          :to="app.to"
          variant="tile"
          @click="$emit('select-app', app.key)"
        >
          <Avatar :label="app.label" :image="app.image" size="lg" shape="square" class="size-7" />
        </RailItem>

        <div class="mt-auto flex flex-col items-center gap-2.5 pt-3">
          <slot name="rail-footer" />
        </div>
      </Rail>
    </template>

    <template v-if="$slots.sidebar" #sidebar>
      <slot name="sidebar" />
    </template>

    <slot />
  </DesktopShell>

  <!-- Sheet rather than a dropdown: on a phone this is the primary way to change
       context, and a sheet gives it a touch target per row instead of a menu row. -->
  <!-- v-model:open, not v-model. BottomSheet's prop is `open`, so a bare
       v-model binds a `modelValue` it never reads and the sheet never opens. -->
  <BottomSheet v-model:open="showMenu" title="Menu">
    <div class="flex flex-col gap-5 p-3 pb-8">
      <div class="flex items-center gap-3 px-1">
        <Avatar
          :label="user.name || user.email || 'Account'"
          :image="user.avatar"
          size="2xl"
        />
        <div class="min-w-0 flex-1">
          <p class="truncate text-base-medium text-ink-gray-8">
            {{ user.name || user.email || 'Account' }}
          </p>
          <p v-if="user.subtitle || user.email" class="truncate text-p-sm text-ink-gray-5">
            {{ user.subtitle || user.email }}
          </p>
        </div>
      </div>

      <section v-if="apps.length > 1">
        <p class="px-1 pb-1 text-p-sm text-ink-gray-5">{{ appsLabel }}</p>
        <router-link
          v-for="app in apps"
          :key="app.key"
          :to="app.to"
          class="flex items-center gap-3 rounded-4 p-2 active:bg-surface-gray-2"
          @click="showMenu = false"
        >
          <Avatar :label="app.label" :image="app.image" size="xl" shape="square" />
          <span class="min-w-0 flex-1 truncate text-base text-ink-gray-8">{{ app.label }}</span>
          <Icon
            v-if="app.key === activeApp"
            name="lucide-check"
            class="size-4 shrink-0 text-ink-gray-6"
          />
        </router-link>
      </section>

      <section v-if="overflowNav.length">
        <p class="px-1 pb-1 text-p-sm text-ink-gray-5">More pages</p>
        <router-link
          v-for="item in overflowNav"
          :key="item.label"
          :to="item.to"
          class="flex items-center gap-3 rounded-4 p-2 active:bg-surface-gray-2"
          @click="showMenu = false"
        >
          <Icon :name="item.icon" class="size-4 shrink-0 text-ink-gray-7" />
          <span class="min-w-0 flex-1 truncate text-base text-ink-gray-8">{{ item.label }}</span>
          <Badge
            v-if="item.badge"
            :theme="item.badge.theme"
            :label="item.badge.label"
            variant="subtle"
          />
        </router-link>
      </section>

      <section v-if="menuItems.length" class="flex flex-col gap-1">
        <Button
          v-for="item in menuItems"
          :key="item.label"
          variant="ghost"
          class="!h-11 w-full !justify-start !px-2"
          :icon-left="item.icon"
          :label="item.label"
          @click="run(item)"
        />
      </section>

      <div>
        <p class="px-1 pb-1.5 text-p-sm text-ink-gray-5">Appearance</p>
        <!-- Three buttons, not a switch: a two-state control cannot express
             "follow the system", and one tap still picks any of the three. -->
        <TabButtons v-model="scheme" :options="tabOptions" fluid />
      </div>

      <Button
        class="w-full"
        variant="subtle"
        theme="red"
        icon-left="lucide-log-out"
        label="Log out"
        @click="logout"
      />
    </div>
  </BottomSheet>
</template>

<script setup>
import { computed, ref } from 'vue'
import {
  Avatar,
  Badge,
  BottomSheet,
  Button,
  DesktopShell,
  Icon,
  MobileNav,
  MobileNavItem,
  MobileShell,
  Rail,
  RailItem,
  TabButtons,
} from '@/ui'
import { useAppearance } from '@/lib/appearance'
import { useIsMobile } from '@/lib/screen'

const props = defineProps({
  /**
   * Rail entries. Each is { key, label, to, image?, description? }.
   * Empty renders no rail at all — a single-app surface should not show a
   * one-item switcher.
   */
  apps: { type: Array, default: () => [] },
  activeApp: { type: String, default: '' },
  /** Heading the mobile sheet gives the rail's entries. */
  appsLabel: { type: String, default: 'Apps' },
  /**
   * Every destination this surface has, in sidebar order:
   * { label, icon, to, active?, badge?, primary? }.
   *
   * The first four reach the bottom bar; the rest, and anything marked
   * `primary: false`, go to the More sheet. Declared once per surface in
   * `lib/nav.js` so the bar and the sidebar cannot drift.
   */
  navItems: { type: Array, default: () => [] },
  /**
   * Actions that live in the rail footer or the sidebar foot on a desktop,
   * e.g. Settings. A phone has neither, so they appear in the More sheet.
   */
  menuItems: { type: Array, default: () => [] },
  /** Identity for the bottom bar's avatar: { name, email, avatar, subtitle }. */
  user: { type: Object, default: () => ({}) },
  /** false when inner panes own their scroll — a list/detail split, say. */
  scroll: { type: Boolean, default: true },
})

defineEmits(['select-app'])

defineSlots()

const isMobile = useIsMobile()
const showMenu = ref(false)

// Four, because the avatar always takes the fifth. `primary: false` opts an
// item out without reordering the sidebar to get it out of the way.
const PRIMARY_SLOTS = 4

const primaryNav = computed(() =>
  props.navItems.filter((item) => item.primary !== false).slice(0, PRIMARY_SLOTS),
)

const overflowNav = computed(() =>
  props.navItems.filter((item) => !primaryNav.value.includes(item)),
)

const { scheme, tabOptions } = useAppearance()

function run(item) {
  showMenu.value = false
  item.onClick?.()
}

// Frappe's own logout clears the session cookie server-side; a client-side
// redirect alone would leave the session valid.
function logout() {
  window.location.href = '/api/method/logout'
}
</script>
"""


THEME_SETTING_VUE = """<!-- Generated by scripts/gen_frontend.py. Edit that, not this file. -->
<template>
  <!--
    SettingsRow + Select, which is what SettingsRow is for: a label and a
    description on the left, one compact control on the right.

    Not ThemeSwitcher. frappe-ui 1.0 marks it `@deprecated` — "Use `Select` with
    `useColorScheme` instead" — and it calls warnDeprecated on every render.
  -->
  <SettingsRow
    title="Appearance"
    description="Light, dark, or matching your system."
  >
    <Select v-model="scheme" :options="selectOptions" />
  </SettingsRow>
</template>

<script setup>
import { Select, SettingsRow } from '@/ui'
import { useAppearance } from '@/lib/appearance'

// Three states, not a toggle. A binary switch cannot express 'follow the
// system', so a user who wants that has to keep changing it by hand twice a day.
const { scheme, selectOptions } = useAppearance()
</script>
"""


EMPTY_STATE_VUE = """<!-- Generated by scripts/gen_frontend.py. Edit that, not this file. -->
<template>
  <div class="grid place-items-center px-6 py-16 text-center">
    <div class="max-w-sm">
      <Icon v-if="icon" :name="icon" class="mx-auto mb-3 size-6 text-ink-gray-4" />
      <p class="text-base-medium text-ink-gray-8">{{ title }}</p>
      <p v-if="description" class="mt-1.5 text-p-base text-ink-gray-6">
        {{ description }}
      </p>
      <div v-if="$slots.action" class="mt-4"><slot name="action" /></div>
    </div>
  </div>
</template>

<script setup>
import { Icon } from '@/ui'

defineProps({
  title: { type: String, required: true },
  description: { type: String, default: '' },
  icon: { type: String, default: '' },
})
</script>
"""


USER_MENU_VUE = """<!-- Generated by scripts/gen_frontend.py. Edit that, not this file. -->
<template>
  <!-- `side` + `align`, not `placement`: frappe-ui removed `placement` in 1.0
       and warns about it in dev, so the menu was never positioned. -->
  <Dropdown :options="options" side="top" align="start" class="w-full">
    <!-- icon-right, not a #suffix holding an <Icon>: Button declares the prop
         and renders it at the library's own size and tone. The #prefix stays a
         slot because an Avatar is not something an icon prop can express. -->
    <Button
      variant="ghost"
      icon-right="lucide-chevron-up"
      class="!h-11 w-full !justify-start !px-2"
    >
      <template #prefix>
        <Avatar :label="displayName" :image="avatar" size="md" />
      </template>
      <span class="min-w-0 flex-1 text-left">
        <span class="block truncate text-base text-ink-gray-8">{{ displayName }}</span>
        <span v-if="subtitle" class="block truncate text-xs text-ink-gray-5">
          {{ subtitle }}
        </span>
      </span>
    </Button>
  </Dropdown>
</template>

<script setup>
import { computed } from 'vue'
import { Avatar, Button, Dropdown } from '@/ui'
import { useAppearance } from '@/lib/appearance'

const props = defineProps({
  name: { type: String, default: '' },
  email: { type: String, default: '' },
  avatar: { type: String, default: '' },
  subtitle: { type: String, default: '' },
  // Entries shown above the standard ones, e.g. Settings for an operator.
  extra: { type: Array, default: () => [] },
})

const displayName = computed(() => props.name || props.email || 'Account')

// Appearance sits here as well as in settings: it is the preference people
// change most often, and hunting for it behind a dialog is the slow path.
//
// Three rows in a group rather than a switch. A two-state control cannot
// express "follow the system", so anyone who wants that ends up flipping it by
// hand twice a day — and a row is the same single tap a switch would be, with
// the current choice visible instead of inferred. `selected` is a
// MenuBaseOption field, so the tick is the library's own.
const { menuGroup } = useAppearance()

const options = computed(() => [
  ...props.extra,
  menuGroup.value,
  {
    label: 'Log out',
    icon: 'lucide-log-out',
    // Frappe's own logout clears the session cookie server-side; a client-side
    // redirect alone would leave the session valid.
    onClick: () => {
      window.location.href = '/api/method/logout'
    },
  },
])
</script>
"""


USAGE_BAR_VUE = """<!-- Generated by scripts/gen_frontend.py. Edit that, not this file. -->
<template>
  <div>
    <div class="flex items-baseline justify-between gap-2">
      <span class="text-p-sm text-ink-gray-6">{{ label }}</span>
      <span class="shrink-0 text-p-sm tabular-nums" :class="valueClass">
        {{ formatted }}
      </span>
    </div>
    <Progress class="mt-1.5" size="sm" :value="percent" :class="barClass" />
    <p v-if="usage?.exceeded" class="mt-1.5 text-p-sm text-ink-red-3">
      {{ exceededHint }}
    </p>
    <p v-else-if="usage?.warn" class="mt-1.5 text-p-sm text-ink-amber-3">
      Approaching the limit.
    </p>
  </div>
</template>

<script setup>
import { computed } from 'vue'
import { Progress } from '@/ui'

const props = defineProps({
  label: { type: String, required: true },
  usage: { type: Object, default: null },
  // 'bytes' for storage and database, 'count' for seats.
  format: { type: String, default: 'bytes' },
  exceededHint: { type: String, default: 'At the limit. Free some space or add more.' },
})

const percent = computed(() => Math.min((props.usage?.fraction || 0) * 100, 100))

// Progress has no `theme`: its fill is always `bg-surface-gray-10`, so the
// colour has to be applied from outside. `class` falls through to the root, and
// the fill is the element inside `role="progressbar"` — `!` because the
// component's own background class is on that same element.
const barClass = computed(() => {
  if (props.usage?.exceeded) return '[&_[role=progressbar]>*]:!bg-surface-red-6'
  if (props.usage?.warn) return '[&_[role=progressbar]>*]:!bg-surface-amber-5'
  return ''
})

const valueClass = computed(() => {
  if (props.usage?.exceeded) return 'text-ink-red-3'
  if (props.usage?.warn) return 'text-ink-amber-3'
  return 'text-ink-gray-7'
})

function bytes(value) {
  if (!value) return '0 B'
  const units = ['B', 'KB', 'MB', 'GB', 'TB']
  const i = Math.min(Math.floor(Math.log(value) / Math.log(1024)), units.length - 1)
  return `${(value / 1024 ** i).toFixed(i === 0 ? 0 : 1)} ${units[i]}`
}

const formatted = computed(() => {
  const u = props.usage
  if (!u) return ''
  if (!u.quota) return props.format === 'bytes' ? bytes(u.used) : String(u.used)
  return props.format === 'bytes'
    ? `${bytes(u.used)} of ${bytes(u.quota)}`
    : `${u.used} of ${u.quota}`
})
</script>
"""


# The icons an app in the registry may use.
#
# frappe-ui renders `lucide-*` names as Tailwind utility classes, and Tailwind's
# JIT only emits CSS for classes it finds as literal strings in the source. An
# icon typed by an operator and stored in a doctype is in no source file, so it
# emits nothing and the launcher shows an empty box.
#
# Writing the set here is what makes those classes exist in the CSS.
ICONS_JS = """\
/**
 * The icons an app in the registry may use.
 *
 * These literals are what make the CSS exist. frappe-ui renders `lucide-*`
 * names as Tailwind utility classes, and the JIT only emits a class it can find
 * as a literal string — so an icon name that only ever exists in the database
 * renders as an empty box. The icons page gives two ways out: a known set
 * written as literals, or `~icons/lucide/*` imports for a genuinely open one. A
 * registry of apps we define is a known set.
 *
 * Never build an icon class by interpolation; the scanner cannot see it.
 *
 * Generated from scripts/app_icons.py, which also writes the doctype's Select
 * options, so the picker and the stored values cannot drift.
 */

export const APP_ICONS = [
{icon_literals}
]

export const DEFAULT_APP_ICON = '{default_icon}'

/** A name we know renders — for anything stored before the set was narrowed. */
export function appIcon(name) {{
  return APP_ICONS.includes(name) ? name : DEFAULT_APP_ICON
}}
""".format(
    icon_literals="\n".join(f"  '{name}'," for name in APP_ICONS),
    default_icon=DEFAULT_APP_ICON,
)


FILES = {
    "index.html": index_html,
    "vite.config.js": vite_config,
    "tailwind.config.js": lambda app, spec: tailwind_config(app),
    "postcss.config.js": lambda app, spec: postcss_config(app),
    "package.json": package_json,
    "eslint.config.js": lambda app, spec: eslint_config(app),
    "src/ui.js": lambda app, spec: UI_BARREL,
    "src/lib/boot.js": lambda app, spec: BOOT_JS,
    "src/lib/errors.js": lambda app, spec: ERRORS_JS,
    "src/lib/sound.js": lambda app, spec: SOUND_JS,
    "src/lib/notify.js": lambda app, spec: NOTIFY_JS,
    "src/lib/socket.js": lambda app, spec: SOCKET_JS,
    "src/lib/resource.js": lambda app, spec: RESOURCE_JS,
    "src/components/EmptyState.vue": lambda app, spec: EMPTY_STATE_VUE,
    "src/components/UserMenu.vue": lambda app, spec: USER_MENU_VUE,
    "src/components/UsageBar.vue": lambda app, spec: USAGE_BAR_VUE,
    "src/lib/screen.js": lambda app, spec: SCREEN_JS,
    "src/lib/appearance.js": lambda app, spec: APPEARANCE_JS,
    "src/lib/list.js": lambda app, spec: LIST_COLUMNS_JS,
    "src/lib/brand.js": lambda app, spec: BRAND_JS,
    "src/lib/icons.js": lambda app, spec: ICONS_JS,
    "src/lib/user.js": lambda app, spec: USER_JS,
    "src/components/AppShell.vue": lambda app, spec: APP_SHELL_VUE,
    "src/components/ThemeSetting.vue": lambda app, spec: THEME_SETTING_VUE,
}

# Written to the app repository root rather than into frontend/.
ROOT_FILES = {
    "package.json": app_root_package_json,
}


def render(app: str, spec: dict) -> dict:
    """Every generated path, relative to apps/<app>/."""
    out = {f"frontend/{name}": fn(app, spec) for name, fn in FILES.items()}
    out.update({name: fn(app, spec) for name, fn in ROOT_FILES.items()})
    return out


def main():
    written = []
    for app, spec in APPS.items():
        base = os.path.join(ROOT, "apps", app)
        for name, content in render(app, spec).items():
            path = os.path.join(base, name)
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w") as fh:
                fh.write(content)
            written.append(f"{app}/{name}")

    print(f"{len(written)} files across {len(APPS)} apps")
    for w in written:
        print(f"  {w}")


if __name__ == "__main__":
    main()
