"""Generate the frontend setup for every SPA in the monorepo.

Two SPAs — the tenant app and the admin control plane — must look and behave
like one product. The risk is drift: two Vite configs, two Tailwind setups, two
different ideas of which components are allowed, diverging a little at a time.

They cannot share an npm workspace, because each app is mirrored to its own
repository for Frappe Cloud and has to be self-contained. So the shared setup is
*generated* into both instead, from the single definition below, exactly as the
doctypes are. `scripts/check_frontend.py` fails CI if either copy is edited by
hand.

Everything here follows frappe-ui's own conventions rather than reimplementing
them: `frappe-ui/vite` owns the dev proxy, build paths and index.html;
`frappe-ui/tailwind` owns the design tokens.

Run: python3 scripts/gen_frontend.py
"""

import json
import os

ROOT = os.path.join(os.path.dirname(__file__), "..")

# frappe-ui 1.x is Vite 7 / Tailwind 3 / vue-router 4. Pinned in one place so the
# two apps can never disagree about a version.
DEPENDENCIES = {
    "frappe-ui": "^1.0.0-beta.55",
    "socket.io-client": "^4.8.1",
    "vue": "^3.5.13",
    "vue-router": "^4.5.0",
}

DEV_DEPENDENCIES = {
    "@vitejs/plugin-vue": "^6.0.0",
    "autoprefixer": "^10.4.20",
    "eslint": "^9.17.0",
    "eslint-plugin-vue": "^9.32.0",
    "postcss": "^8.5.0",
    "tailwindcss": "^3.4.17",
    "vite": "^7.0.0",
}

APPS = {
    "oneapp": {
        "route": "/one",
        "title": "OneApp",
        # Doctypes to generate TypeScript definitions for.
        "types": {"oneapp": ["OneApp Site State"]},
    },
    "oneapp_control": {
        "route": "/admin",
        "title": "OneApp Admin",
        "types": {
            "oneapp_control": [
                "Tenant", "Shard", "Plan", "Subscription",
                "Provisioning Job", "Credit Ledger Entry", "OneApp App",
            ]
        },
    },
}

BANNER = "// Generated by scripts/gen_frontend.py. Edit that, not this file.\n"


def vite_config(app: str, spec: dict) -> str:
    types = json.dumps(spec["types"], indent=2).replace('"', "'")
    html_name = spec["route"].lstrip("/")
    return BANNER + f"""
import {{ defineConfig }} from 'vite'
import vue from '@vitejs/plugin-vue'
import frappeui from 'frappe-ui/vite'
import path from 'node:path'

// frappe-ui's plugin owns the parts that are easy to get subtly wrong: it
// proxies /api, /app, /assets, /files and /private to the bench it detects from
// common_site_config.json, and it emits ../{app}/www/<route>.html so the SPA is
// served by Frappe itself. Hand-rolling any of that is how the two apps drift.
export default defineConfig({{
  plugins: [
    frappeui({{
      frontendRoute: '{spec["route"]}',
      // Given explicitly rather than inferred. frappe-ui derives these by
      // walking up for a bench layout (a directory with both sites/ and apps/),
      // which exists on Frappe Cloud but not in this monorepo — so inference
      // returns null here and the production build fails with
      // "indexHtmlPath is required". Stating them makes the build identical
      // everywhere: monorepo, bench, and CI.
      buildConfig: {{
        outDir: path.resolve(__dirname, '../{app}/public/frontend'),
        indexHtmlPath: '../{app}/www/{html_name}.html',
      }},
      frappeTypes: {{
        input: {types},
      }},
    }}),
    vue(),
  ],
  resolve: {{
    alias: {{ '@': path.resolve(__dirname, 'src') }},
  }},
}})
"""


def index_html(app: str, spec: dict) -> str:
    """Vite's entry document.

    The frappe-ui plugin transforms this into ../<app>/www/<route>.html at build
    time — it does not create it, so this file has to exist.

    The inline theme script runs before first paint. Without it the page flashes
    white before Tailwind loads, because `bg-surface-base` only resolves once the
    stylesheet arrives.
    """
    return f"""<!doctype html>
<html class="h-full" lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover" />
    <title>{spec["title"]}</title>
    <script>
      ;(function () {{
        try {{
          var stored = localStorage.getItem('theme')
          var theme = stored === 'light' || stored === 'dark' ? stored : null
          if (!theme) {{
            theme = window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light'
          }}
          document.documentElement.setAttribute('data-theme', theme)
          document.documentElement.style.backgroundColor =
            theme === 'dark' ? '#171717' : '#ffffff'
        }} catch (e) {{}}
      }})()
    </script>
    <meta name="theme-color" media="(prefers-color-scheme: light)" content="#ffffff" />
    <meta name="theme-color" media="(prefers-color-scheme: dark)" content="#171717" />
  </head>
  <body class="h-full bg-surface-base">
    <div id="app" class="h-full"></div>
    <script type="module" src="/src/main.js"></script>
  </body>
</html>
"""


def tailwind_config(app: str) -> str:
    return BANNER + """
import preset, { content as frappeUIContent } from 'frappe-ui/tailwind'

// Tailwind 3 does not merge `content` from a preset, so frappe-ui's own source
// globs have to be listed here or half the component styles are purged out.
export default {
  presets: [preset],
  content: [...frappeUIContent, './index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
}
"""


def postcss_config(app: str) -> str:
    return BANNER + """
export default {
  plugins: { tailwindcss: {}, autoprefixer: {} },
}
"""


def app_root_package_json(app: str, spec: dict) -> str:
    """Repo-root package.json.

    Frappe Cloud installs and builds an app by running yarn at its repository
    root, so this is what makes the SPA exist in a deployed bench at all.
    Without it the build silently does nothing and the www page 404s, because
    the HTML is emitted by the Vite build rather than committed.
    """
    return json.dumps(
        {
            "name": app.replace("_", "-"),
            "private": True,
            "type": "module",
            "_generated": "scripts/gen_frontend.py",
            "scripts": {
                "postinstall": "cd frontend && yarn install",
                "dev": "cd frontend && yarn dev",
                "build": "cd frontend && yarn build",
                "lint": "cd frontend && yarn lint",
            },
        },
        indent=2,
    ) + "\n"


def package_json(app: str, spec: dict) -> str:
    return json.dumps(
        {
            "name": f"{app.replace('_', '-')}-frontend",
            "private": True,
            "type": "module",
            "version": "0.0.1",
            "_generated": "scripts/gen_frontend.py",
            "scripts": {
                "dev": "vite",
                "build": "vite build",
                "preview": "vite preview",
                "lint": "eslint src",
            },
            "dependencies": DEPENDENCIES,
            "devDependencies": DEV_DEPENDENCIES,
        },
        indent=2,
    ) + "\n"


def eslint_config(app: str) -> str:
    return BANNER + """
import pluginVue from 'eslint-plugin-vue'

// The guard. Every native control here has a frappe-ui equivalent, and using the
// raw element is how a design system quietly stops being one — a plain <button>
// looks close enough in isolation and wrong next to everything else.
//
// Escape hatch is a one-line eslint-disable with a reason, so bypassing it is a
// visible decision rather than an accident.
const BANNED = [
  { element: 'button', message: 'Use <Button> from @/ui instead of a raw <button>.' },
  { element: 'input', message: 'Use <TextInput>, <FormControl>, <Checkbox> or <Switch> from @/ui.' },
  { element: 'select', message: 'Use <Select> or <Autocomplete> from @/ui.' },
  { element: 'textarea', message: 'Use <Textarea> or <FormControl type="textarea"> from @/ui.' },
  { element: 'dialog', message: 'Use <Dialog> from @/ui.' },
  { element: 'table', message: 'Use <ListView> from frappe-ui/list.' },
]

export default [
  ...pluginVue.configs['flat/recommended'],
  {
    files: ['src/**/*.vue'],
    rules: {
      'vue/no-restricted-html-elements': ['error', ...BANNED],
      'vue/multi-word-component-names': 'off',
      'vue/no-v-html': 'error',

      // Formatting is a formatter's job. Left on, these produce dozens of
      // warnings per file and train everyone to ignore lint output — which is
      // where the rules that actually matter live.
      'vue/max-attributes-per-line': 'off',
      'vue/singleline-html-element-content-newline': 'off',
      'vue/html-self-closing': 'off',
      'vue/html-indent': 'off',
      'vue/html-closing-bracket-newline': 'off',
      'vue/attributes-order': 'off',
      'vue/first-attribute-linebreak': 'off',
    },
  },
  {
    // The shared runtime is exempt — it is what wraps frappe-ui.
    files: ['src/**/*.{js,vue}'],
    ignores: ['src/ui.js', 'src/lib/**'],
    rules: {
      'no-restricted-imports': ['error', {
        paths: [
          {
            name: 'frappe-ui',
            // Two separate reasons, both load-bearing:
            //  - components: '@/ui' is the one reviewable list of what is allowed
            //  - data/notify: '@/lib/resource' and '@/lib/notify' are what apply
            //    response unwrapping, Frappe error parsing, toasts and sound
            message:
              "Import components from '@/ui', data helpers from '@/lib/resource', " +
              "and toasts from '@/lib/notify'. Going direct skips error parsing, " +
              'response unwrapping and notification sound.',
          },
          {
            name: 'socket.io-client',
            message: "Use onDoctypeChange from '@/lib/socket' — one shared, " +
              'reference-counted socket per app.',
          },
        ],
      }],
      // console.error is deliberate in the error normaliser; noise elsewhere.
      'no-console': ['warn', { allow: ['warn', 'error'] }],
    },
  },
]
"""


# Components the design system sanctions. Adding one here is the deliberate act
# that makes it available to both apps at once.
UI_BARREL = BANNER + """
/**
 * The sanctioned frappe-ui surface.
 *
 * Both SPAs import components from here rather than from 'frappe-ui' directly,
 * so what the product is allowed to use is a single reviewable list instead of
 * whatever each file happened to reach for. ESLint enforces it.
 */

export {
  // Layout and shell
  DesktopShell,
  MobileShell,
  MobileNav,
  Sidebar,
  Rail,
  PageHeader,
  ScrollArea,
  Divider,
  Tabs,
  TabButtons,

  // Actions
  Button,
  Dropdown,
  Menu,
  ContextMenu,

  // Form controls
  FormControl,
  FormLabel,
  TextInput,
  Textarea,
  Password,
  Select,
  Combobox,
  MultiSelect,
  Checkbox,
  Switch,
  Radio,
  Slider,
  Rating,
  DatePicker,
  TimePicker,
  Duration,
  FileUploader,
  ErrorMessage,

  // Feedback and status
  Alert,
  Badge,
  Progress,
  Spinner,
  LoadingIndicator,
  LoadingText,
  Skeleton,
  Toast,
  Tooltip,

  // Overlays
  Dialog,
  Popover,
  HoverCard,
  BottomSheet,
  SettingsDialog,
  KeyboardShortcut,
  KeyboardShortcutsDialog,

  // Display
  Avatar,
  Icon,
  Breadcrumbs,
  Tree,
  ItemListRow,
  ThemeSwitcher,

  // Root provider — wraps the app so toasts and dialogs work.
  FrappeUIProvider,

  // Imperative helpers
  toast,
  dialog,

  // Composables
  usePageMeta,
  useColorScheme,
  useKeyboardShortcut,
  useShellScrolled,
  useFileUpload,

  // Directives
  vFocus,
  vOnOutsideClick,

  // Data and utilities
  call,
  frappeRequest,
  setConfig,
  getConfig,
  dayjs,
  dayjsLocal,
  debounce,
} from 'frappe-ui'
"""



# --------------------------------------------------------------------------- #
# Shared runtime
#
# Data fetching, realtime, error rendering and notifications are identical in
# both SPAs by construction. Written once here, generated into both, and
# enforced by ESLint so no page can quietly bypass them.
# --------------------------------------------------------------------------- #

BOOT_JS = BANNER + """
/**
 * Boot data injected by frappe-ui's vite plugin.
 *
 * The plugin's jinjaBootData sub-plugin writes the www page's `boot` context
 * onto `window`, so whatever the page controller puts there is available before
 * the app mounts. Everything here degrades to a sane default, because the dev
 * server serves index.html without Jinja and would otherwise crash on boot.
 */

// The plugin emits `window["<key>"] = <value>` for each key in the page's boot
// context — so `boot.site_name` lands as `window.site_name`, not under a `boot`
// object. Reading window.boot would silently yield undefined and leave the
// socket pointed at the wrong host.
const read = (key, fallback) => (window[key] !== undefined ? window[key] : fallback)

export const siteName = read('site_name', window.location.hostname)
export const socketioPort = read('socketio_port', 9000)
export const csrfToken = read('csrf_token', null)
export const isDev = import.meta.env.DEV

export default { siteName, socketioPort, csrfToken, isDev }
"""


ERRORS_JS = BANNER + """
/**
 * Frappe error normalisation.
 *
 * Frappe reports failures in several shapes: a FrappeResponseError from
 * frappe-ui's fetch layer, a JSON body with `_server_messages` (itself a
 * JSON-encoded array of JSON-encoded objects), an `exception` traceback string,
 * or a bare Error. Rendering any of those raw gives users a stack trace or
 * "[object Object]".
 *
 * This flattens all of them to { title, message, detail }, where `message` is
 * safe to show and `detail` is for the console.
 */

/** Strip the HTML Frappe puts in server messages. */
function stripTags(value) {
  if (typeof value !== 'string') return value
  const el = document.createElement('div')
  el.innerHTML = value
  return (el.textContent || '').trim()
}

/** `_server_messages` is a JSON string containing JSON strings. */
function parseServerMessages(raw) {
  if (!raw) return []
  try {
    const outer = typeof raw === 'string' ? JSON.parse(raw) : raw
    return (Array.isArray(outer) ? outer : [outer])
      .map((entry) => {
        try {
          return typeof entry === 'string' ? JSON.parse(entry) : entry
        } catch {
          return { message: entry }
        }
      })
      .filter(Boolean)
  } catch {
    return []
  }
}

/** Last frame of a traceback is the only useful line for a user-facing hint. */
function lastTracebackLine(exception) {
  if (typeof exception !== 'string') return ''
  const lines = exception.trim().split('\\n').filter(Boolean)
  return lines.length ? lines[lines.length - 1].trim() : ''
}

export function normalizeError(error) {
  if (!error) return { title: 'Something went wrong', message: '', detail: null }

  const messages = parseServerMessages(
    error.messages || error._server_messages || error.response?._server_messages,
  )

  const first = messages[0] || {}
  const fromServer = stripTags(first.message)

  // FrappeResponseError already carries the parsed fields.
  const title =
    first.title ||
    error.title ||
    (error.name === 'FrappeResponseError' ? 'Request failed' : null) ||
    'Something went wrong'

  const message =
    fromServer ||
    stripTags(error.message) ||
    lastTracebackLine(error.exception) ||
    'No further detail was returned.'

  return {
    title: stripTags(title),
    message,
    // Extra server messages beyond the first, shown as additional lines.
    extra: messages.slice(1).map((m) => stripTags(m.message)).filter(Boolean),
    indicator: first.indicator || error.indicator || 'red',
    detail: error.exception || error.stack || null,
    raw: error,
  }
}

export function errorText(error) {
  const { title, message } = normalizeError(error)
  return message && message !== title ? `${title}: ${message}` : title
}
"""


SOUND_JS = BANNER + """
/**
 * Notification sounds.
 *
 * Synthesised with WebAudio rather than shipped as audio files: two short tones
 * need no network request, no asset pipeline, and no licensing.
 *
 * Browsers refuse to start an AudioContext before a user gesture, so the
 * context is created lazily on first play and every failure is swallowed — a
 * silent notification is fine, a thrown error inside a toast is not.
 */

const STORAGE_KEY = 'oneapp:sound'

let context = null

function audioContext() {
  if (context) return context
  const Ctor = window.AudioContext || window.webkitAudioContext
  if (!Ctor) return null
  try {
    context = new Ctor()
  } catch {
    context = null
  }
  return context
}

export function soundEnabled() {
  try {
    return localStorage.getItem(STORAGE_KEY) !== 'off'
  } catch {
    // Private mode and blocked storage both throw; default to on.
    return true
  }
}

export function setSoundEnabled(enabled) {
  try {
    localStorage.setItem(STORAGE_KEY, enabled ? 'on' : 'off')
  } catch {
    /* nothing we can do, and nothing worth failing for */
  }
}

/** Two notes: rising for success, falling for failure. */
const TONES = {
  success: [660, 880],
  error: [440, 330],
}

function playTone(frequencies) {
  const ctx = audioContext()
  if (!ctx) return

  // Autoplay policy may leave it suspended until a gesture.
  if (ctx.state === 'suspended') ctx.resume().catch(() => {})

  const now = ctx.currentTime
  frequencies.forEach((frequency, index) => {
    const start = now + index * 0.09
    const osc = ctx.createOscillator()
    const gain = ctx.createGain()

    osc.type = 'sine'
    osc.frequency.value = frequency

    // Short envelope; a click is what you get without the ramps.
    gain.gain.setValueAtTime(0, start)
    gain.gain.linearRampToValueAtTime(0.05, start + 0.01)
    gain.gain.exponentialRampToValueAtTime(0.0001, start + 0.16)

    osc.connect(gain).connect(ctx.destination)
    osc.start(start)
    osc.stop(start + 0.18)
  })
}

export function playSound(kind) {
  if (!soundEnabled()) return
  try {
    playTone(TONES[kind] || TONES.success)
  } catch {
    /* audio is a nicety; never let it break a notification */
  }
}
"""


NOTIFY_JS = BANNER + """
/**
 * Notifications.
 *
 * Every mutation reports its outcome and every failure is rendered from a
 * normalised Frappe error, so users never see a raw traceback or a silent
 * no-op. Both play a short tone.
 *
 * Pages should not call `toast` directly — these wrappers are what guarantee
 * the sound and the error parsing happen.
 */

import { toast } from 'frappe-ui'

import { normalizeError } from './errors'
import { playSound } from './sound'

export function notifySuccess(message, options = {}) {
  playSound('success')
  return toast.success(message, options)
}

export function notifyError(error, options = {}) {
  const { title, message, extra, detail } = normalizeError(error)

  // The traceback goes to the console, never the toast.
  if (detail) console.error(title, detail)

  playSound('error')
  return toast.error(title, {
    description: [message, ...(extra || [])].filter(Boolean).join('\\n'),
    duration: 8000,
    ...options,
  })
}

export function notifyInfo(message, options = {}) {
  return toast.info(message, options)
}

export { toast }
"""


SOCKET_JS = BANNER + """
/**
 * Frappe realtime.
 *
 * Frappe's socket.io server namespaces connections by site and pushes a
 * `list_update` event whenever a document changes. Subscribing to the doctypes
 * a page renders keeps it fresh without polling.
 *
 * One socket per app, shared by every subscriber. Subscriptions are reference
 * counted so a component unmounting does not cut off another that still needs
 * the same doctype.
 */

import { io } from 'socket.io-client'
import { onScopeDispose, getCurrentScope } from 'vue'

import { siteName, socketioPort, isDev } from './boot'

let socket = null
const subscribers = new Map()

function socketUrl() {
  // In development Vite serves the SPA, so the socket has to be addressed
  // directly on the bench's socketio port. In production it is proxied on the
  // site's own origin.
  if (isDev) {
    return `${window.location.protocol}//${window.location.hostname}:${socketioPort}/${siteName}`
  }
  return `${window.location.origin}/${siteName}`
}

export function getSocket() {
  if (socket) return socket

  socket = io(socketUrl(), {
    withCredentials: true,
    reconnection: true,
    reconnectionAttempts: Infinity,
    // Back off rather than hammering a bench that is restarting.
    reconnectionDelay: 1000,
    reconnectionDelayMax: 10000,
  })

  socket.on('connect', () => {
    // Re-subscribe after a reconnect; the server forgets on disconnect.
    for (const doctype of subscribers.keys()) {
      socket.emit('doctype_subscribe', doctype)
    }
  })

  socket.on('list_update', (data) => {
    const handlers = subscribers.get(data?.doctype)
    if (handlers) handlers.forEach((fn) => fn(data.name, data))
  })

  return socket
}

/**
 * Call `handler` whenever any document of `doctype` changes.
 * Returns an unsubscribe function, and cleans up automatically inside a
 * component scope.
 */
export function onDoctypeChange(doctype, handler) {
  const sock = getSocket()

  if (!subscribers.has(doctype)) {
    subscribers.set(doctype, new Set())
    sock.emit('doctype_subscribe', doctype)
  }
  subscribers.get(doctype).add(handler)

  const stop = () => {
    const handlers = subscribers.get(doctype)
    if (!handlers) return
    handlers.delete(handler)
    if (handlers.size === 0) {
      subscribers.delete(doctype)
      sock.emit('doctype_unsubscribe', doctype)
    }
  }

  if (getCurrentScope()) onScopeDispose(stop)
  return stop
}

export function closeSocket() {
  if (!socket) return
  socket.close()
  socket = null
  subscribers.clear()
}
"""


RESOURCE_JS = BANNER + """
/**
 * The single way this app talks to Frappe.
 *
 * Wraps frappe-ui's useCall so that every request in both SPAs gets the same
 * treatment:
 *
 *   - responses unwrapped, so pages read `data` rather than `data.message`
 *   - failures rendered through the Frappe error normaliser and toasted
 *   - mutations announce their result
 *   - lists refresh over the socket instead of polling
 *
 * ESLint forbids importing useCall or call directly, so this cannot be bypassed
 * without a visible disable comment.
 */

import { useCall, call as rawCall } from 'frappe-ui'

import { notifyError, notifySuccess } from './notify'
import { onDoctypeChange } from './socket'

/**
 * Unwrap Frappe's envelope.
 *
 * Depending on the endpoint a response arrives as the value, as `{message: …}`,
 * or occasionally as `{message: {message: …}}` when a whitelisted method
 * returns something already enveloped. Pages should never have to care.
 */
export function normalize(data) {
  let value = data
  let depth = 0

  while (
    value &&
    typeof value === 'object' &&
    !Array.isArray(value) &&
    'message' in value &&
    Object.keys(value).length === 1 &&
    depth < 3
  ) {
    value = value.message
    depth += 1
  }

  return value
}

/**
 * A read. Toasts on failure; silent on success.
 *
 * `watch` names doctypes whose changes should trigger a refetch over the
 * socket.
 */
export function useResource(url, options = {}) {
  const { watch: watchDoctypes = [], silent = false, transform, onError, ...rest } = options

  const resource = useCall({
    url,
    transform: (data) => {
      const value = normalize(data)
      return transform ? transform(value) : value
    },
    onError: (error) => {
      if (!silent) notifyError(error)
      onError?.(error)
    },
    ...rest,
  })

  for (const doctype of watchDoctypes) {
    onDoctypeChange(doctype, () => resource.reload())
  }

  return resource
}

/**
 * A write. Always announces its outcome — a save that appears to do nothing is
 * indistinguishable from a broken one.
 */
export function useAction(url, options = {}) {
  const {
    successMessage = 'Saved',
    silent = false,
    transform,
    onSuccess,
    onError,
    ...rest
  } = options

  return useCall({
    url,
    method: 'POST',
    immediate: false,
    transform: (data) => {
      const value = normalize(data)
      return transform ? transform(value) : value
    },
    onSuccess: (data) => {
      if (!silent && successMessage) notifySuccess(successMessage)
      onSuccess?.(data)
    },
    onError: (error) => {
      if (!silent) notifyError(error)
      onError?.(error)
    },
    ...rest,
  })
}

/**
 * One-off call for imperative code. Normalised and toasted like everything else.
 */
export async function callMethod(method, params = {}, options = {}) {
  const { successMessage, silent = false } = options
  try {
    const data = normalize(await rawCall(method, params))
    if (successMessage && !silent) notifySuccess(successMessage)
    return data
  } catch (error) {
    if (!silent) notifyError(error)
    throw error
  }
}
"""


FILES = {
    "index.html": index_html,
    "vite.config.js": vite_config,
    "tailwind.config.js": lambda app, spec: tailwind_config(app),
    "postcss.config.js": lambda app, spec: postcss_config(app),
    "package.json": package_json,
    "eslint.config.js": lambda app, spec: eslint_config(app),
    "src/ui.js": lambda app, spec: UI_BARREL,
    "src/lib/boot.js": lambda app, spec: BOOT_JS,
    "src/lib/errors.js": lambda app, spec: ERRORS_JS,
    "src/lib/sound.js": lambda app, spec: SOUND_JS,
    "src/lib/notify.js": lambda app, spec: NOTIFY_JS,
    "src/lib/socket.js": lambda app, spec: SOCKET_JS,
    "src/lib/resource.js": lambda app, spec: RESOURCE_JS,
}

# Written to the app repository root rather than into frontend/.
ROOT_FILES = {
    "package.json": app_root_package_json,
}


def render(app: str, spec: dict) -> dict:
    """Every generated path, relative to apps/<app>/."""
    out = {f"frontend/{name}": fn(app, spec) for name, fn in FILES.items()}
    out.update({name: fn(app, spec) for name, fn in ROOT_FILES.items()})
    return out


def main():
    written = []
    for app, spec in APPS.items():
        base = os.path.join(ROOT, "apps", app)
        for name, content in render(app, spec).items():
            path = os.path.join(base, name)
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w") as fh:
                fh.write(content)
            written.append(f"{app}/{name}")

    print(f"{len(written)} files across {len(APPS)} apps")
    for w in written:
        print(f"  {w}")


if __name__ == "__main__":
    main()
