"""The catalogue: what we have to translate, and what somebody already did.

Frappe's translation mechanism is gettext, and the msgid is the English string
itself — `_("Save")`, not `_("btn.save")`. That is the whole reason this product
uses it rather than a key scheme of its own: the framework merges every
installed app's catalogue into one lookup, so a sentence we write that Frappe or
ERPNext has already translated into forty languages resolves for free, in every
one of them, with nothing in our own files.

Which makes the interesting question not "what do we say" but "what do we say
that nobody has said before". This answers it:

    python3 scripts/i18n.py stat          # free / translated / owed
    python3 scripts/i18n.py gap ar        # what is still ours to write
    python3 scripts/i18n.py sync          # bring the .po files up to the POT
    python3 scripts/i18n.py load DIR      # read translations back in, as TSV

The POT itself is regenerated by the framework and needs a site, so it is not
here:

    scripts/dev.sh run scripts/i18n_pot.py

Two things worth knowing before editing any of this.

**A msgid is a promise.** Change an English sentence and every translation of it
is orphaned — gettext matches on the string, so a comma is a different message.
`sync` keeps what it can and reports what it dropped; it never guesses.

**Our .po files hold only what is ours.** A msgid Frappe already translates is
deliberately absent, because carrying it would mean maintaining a second, worse
Arabic for "Save" that shadows theirs the moment ours loads later. `sync`
removes any that drift in.
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent

# Where the framework and its accounting app keep theirs. Read-only, and read
# from the bench rather than vendored: they are updated by `bench update`, and a
# copy here would be a snapshot that silently goes stale.
BENCH = pathlib.Path("/home/frappe/bench1/apps")
UPSTREAM = ("frappe", "erpnext")

# The one app a customer reads. `oneapp_control` is deliberately not here: it
# is the operator console, every reader of it works for us, and translating our
# own fleet vocabulary into Arabic would be work nobody would ever see. It still
# gets a POT — that is free, and the day we hire an operator who does not read
# English the catalogue is one `sync` away.
OURS = ("oneapp",)

# Same argument one level down. `screens/ops/` is the operator console rendered
# inside the tenant SPA, so its strings land in oneapp's POT beside the
# customer's. A msgid that appears *only* there is operator vocabulary — bench
# groups, shards, dunning ladders — and is left in English.
OPERATOR = "screens/ops/"

# The languages we sell in. English is not here and never will be: the msgid is
# the English, so an English reader is served by the absence of a catalogue.
LANGUAGES = ("ar", "de")


# --------------------------------------------------------------------------- #
# Reading and writing PO
# --------------------------------------------------------------------------- #
#
# Deliberately not `babel` or `polib`: this runs from `python3 scripts/i18n.py`
# with nothing installed, which is what makes it usable in a shell that is not
# the bench's virtualenv. The format it handles is the subset our own files and
# Frappe's are written in — one msgid, one msgstr, optional msgctxt, continued
# across quoted lines — and it round-trips its own output exactly.

STRING = re.compile(r'^"(.*)"$')


def _unquote(line: str) -> str:
	"""One PO string literal as its value."""
	body = STRING.match(line.strip())
	if not body:
		return ""
	return (
		body.group(1)
		.replace(r"\\", "\x00")
		.replace(r"\n", "\n")
		.replace(r"\t", "\t")
		.replace(r"\"", '"')
		.replace("\x00", "\\")
	)


def _quote(value: str) -> str:
	"""A value as PO literals — one line, or a run of them for a long string.

	Long strings are broken after a space rather than at a fixed column, so a
	diff of a reworded sentence is the words that changed.
	"""
	escaped = (
		value.replace("\\", r"\\").replace('"', r"\"").replace("\t", r"\t").replace("\n", r"\n")
	)
	if len(escaped) <= 72:
		return f'"{escaped}"'

	lines, current = [], ""
	for word in escaped.split(" "):
		if current and len(current) + len(word) + 1 > 72:
			lines.append(current + " ")
			current = word
		else:
			current = f"{current} {word}" if current else word
	if current:
		lines.append(current)
	return '""\n' + "\n".join(f'"{one}"' for one in lines)


def read(path) -> dict:
	"""`{(msgid, msgctxt): msgstr}` for a .po or .pot file. `{}` if absent."""
	path = pathlib.Path(path)
	if not path.exists():
		return {}

	out, field = {}, None
	entry = {"msgid": "", "msgstr": "", "msgctxt": ""}

	def flush():
		if entry["msgid"]:
			out[(entry["msgid"], entry["msgctxt"])] = entry["msgstr"]

	for line in path.read_text(encoding="utf-8").splitlines():
		stripped = line.strip()
		# A comment or a blank line ends a continuation but not the entry: PO
		# puts `#: where.vue:12` *between* the msgstr and the next msgid.
		if not stripped or stripped.startswith("#"):
			field = None
			continue
		if stripped.startswith('"'):
			if field:
				entry[field] += _unquote(stripped)
			continue
		for name in ("msgctxt", "msgid", "msgstr"):
			if stripped.startswith(name):
				# A new entry starts at whichever of msgctxt/msgid comes first,
				# so flush only when one arrives after we already have a msgid.
				if name != "msgstr" and entry["msgid"]:
					flush()
					entry = {"msgid": "", "msgstr": "", "msgctxt": ""}
				field = name
				entry[name] = _unquote(stripped[len(name) :].strip())
				break
		else:
			field = None
	flush()
	return out


HEADER = """\
# {language} translation for {app}.
#
# The msgid is the English sentence, so this file holds only what nobody
# upstream has translated already — see scripts/i18n.py.
msgid ""
msgstr ""
"MIME-Version: 1.0\\n"
"Content-Type: text/plain; charset=UTF-8\\n"
"Content-Transfer-Encoding: 8bit\\n"
"Language: {lang}\\n"
"""

NAMED = {"ar": "Arabic", "de": "German"}


def write(path, lang: str, app: str, entries: dict) -> None:
	"""One .po file, msgids in English alphabetical order.

	Sorted rather than in source order because source order is line numbers,
	and a file that reorders itself every time a component moves is a diff
	nobody can read.
	"""
	out = [HEADER.format(language=NAMED.get(lang, lang), app=app, lang=lang).rstrip("\n")]
	for (msgid, ctx), msgstr in sorted(entries.items()):
		out.append("")
		if ctx:
			out.append(f"msgctxt {_quote(ctx)}")
		out.append(f"msgid {_quote(msgid)}")
		out.append(f"msgstr {_quote(msgstr)}")
	pathlib.Path(path).write_text("\n".join(out) + "\n", encoding="utf-8")


# --------------------------------------------------------------------------- #
# Who has already said it
# --------------------------------------------------------------------------- #


def upstream(lang: str) -> dict:
	"""Every msgid the framework and ERPNext translate into `lang`.

	Keyed by msgid alone, context dropped: a context narrows a translation, and
	for the question this asks — "is this sentence already covered" — the
	uncontexted answer is the one that matters.
	"""
	have = {}
	for app in UPSTREAM:
		path = BENCH / app / app / "locale" / f"{lang}.po"
		if not path.exists():
			print(f"  no {app}/{lang}.po on the bench — coverage will read low")
			continue
		for (msgid, _ctx), msgstr in read(path).items():
			if msgstr:
				have.setdefault(msgid, msgstr)
	return have


LOCATION = re.compile(r"^#: (.*)$", re.M)
MSGID = re.compile(r'^msgid (".*(?:\n".*)*)', re.M)


def pot(app: str) -> dict:
	"""Every msgid the extractor found, minus the ones only an operator sees.

	The POT records where each string came from, which is the only thing that
	can tell a customer's sentence from an operator's: they are written in the
	same SPA, in the same components, and differ solely by which folder the
	file that says them lives in.
	"""
	path = ROOT / "apps" / app / app / "locale" / "main.pot"
	if not path.exists():
		return {}

	operator_only = set()
	for block in path.read_text(encoding="utf-8").split("\n\n"):
		places = " ".join(LOCATION.findall(block)).split()
		found = MSGID.search(block)
		if not places or not found:
			continue
		text = "".join(_unquote(one) for one in found.group(1).splitlines())
		if text and all(OPERATOR in one for one in places):
			operator_only.add(text)

	return {key: value for key, value in read(path).items() if key[0] not in operator_only}


def po(app: str, lang: str) -> dict:
	return read(ROOT / "apps" / app / app / "locale" / f"{lang}.po")


def ours(app: str, lang: str) -> dict:
	"""The msgids in this app that nobody upstream translates, as
	`{(msgid, ctx): existing translation or ""}`."""
	covered = upstream(lang)
	return {
		key: ""
		for key in pot(app)
		if key[0] not in covered
	}


# --------------------------------------------------------------------------- #
# The commands
# --------------------------------------------------------------------------- #


def cmd_stat(args) -> int:
	for lang in args or LANGUAGES:
		covered = upstream(lang)
		print(f"\n{NAMED.get(lang, lang)} ({lang}) — {len(covered)} msgids upstream")
		for app in OURS:
			total = pot(app)
			if not total:
				print(f"  {app}: no main.pot — run scripts/dev.sh run scripts/i18n_pot.py")
				continue
			free = [key for key in total if key[0] in covered]
			mine = po(app, lang)
			done = [key for key in total if key not in free and mine.get(key)]
			owed = len(total) - len(free) - len(done)
			print(
				f"  {app}: {len(total)} strings — {len(free)} free, "
				f"{len(done)} translated, {owed} owed"
			)
	return 0


def cmd_gap(args) -> int:
	"""The msgids still owed, one per line, so a work list can be piped."""
	lang = (args or ["ar"])[0]
	covered = upstream(lang)
	for app in OURS:
		mine = po(app, lang)
		for msgid, ctx in sorted(pot(app)):
			if msgid in covered or mine.get((msgid, ctx)):
				continue
			print(f"{app}\t{ctx}\t{msgid}")
	return 0


def cmd_sync(args) -> int:
	"""Bring every .po into step with the POT.

	Three things happen, and only the first two ever touch a translation: a new
	msgid arrives empty, a msgid that upstream has since translated is dropped
	(theirs is better maintained than ours would be), and a msgid that no longer
	exists anywhere is dropped and named, because a reworded sentence looks
	exactly like a deleted one from here.
	"""
	for lang in args or LANGUAGES:
		covered = upstream(lang)
		for app in OURS:
			total = pot(app)
			if not total:
				continue
			mine = po(app, lang)
			wanted = {key: mine.get(key, "") for key in total if key[0] not in covered}

			orphans = sorted(
				msgid for (msgid, _c), text in mine.items() if text and (msgid, _c) not in wanted
			)
			write(ROOT / "apps" / app / app / "locale" / f"{lang}.po", lang, app, wanted)
			owed = sum(1 for text in wanted.values() if not text)
			print(f"{app}/{lang}.po — {len(wanted)} ours, {owed} owed")
			for one in orphans:
				print(f"    dropped (no longer in the POT): {one[:70]}")
	return 0


def cmd_load(args) -> int:
	"""Read translations back in from tab-separated files.

	    python3 scripts/i18n.py load <directory>

	One file per surface, `english<TAB>arabic<TAB>german`, which is the shape a
	translator can be handed and can hand back without knowing what a .po file
	is. A line whose English is not a msgid we owe is reported and skipped —
	usually it means the wording moved after the file went out, and silently
	dropping it would lose a translation nobody knew was missing.
	"""
	if not args:
		print("which directory?")
		return 1

	got = {}
	for path in sorted(pathlib.Path(args[0]).glob("*.tsv")):
		for number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
			if not line.strip():
				continue
			fields = line.split("\t")
			if len(fields) != 3:
				print(f"  {path.name}:{number} is not three fields — skipped")
				continue
			english, *rest = fields
			got[english.replace("\\n", "\n")] = rest

	for at, lang in enumerate(LANGUAGES):
		covered = upstream(lang)
		for app in OURS:
			mine = po(app, lang)
			wanted, filled, unknown = {}, 0, 0
			for key in pot(app):
				if key[0] in covered:
					continue
				said = got.get(key[0], [None, None])[at]
				wanted[key] = said or mine.get(key, "")
				filled += 1 if wanted[key] else 0
			for english in got:
				if not any(english == msgid for msgid, _c in wanted):
					unknown += 1
			write(ROOT / "apps" / app / app / "locale" / f"{lang}.po", lang, app, wanted)
			print(f"{app}/{lang}.po — {filled} of {len(wanted)} translated")
			if unknown:
				print(f"    {unknown} lines were for a msgid this app no longer has")
	return 0


COMMANDS = {"stat": cmd_stat, "gap": cmd_gap, "sync": cmd_sync, "load": cmd_load}


def main() -> int:
	if len(sys.argv) < 2 or sys.argv[1] not in COMMANDS:
		print(__doc__.split("Two things worth knowing")[0].strip())
		return 1
	return COMMANDS[sys.argv[1]](sys.argv[2:])


if __name__ == "__main__":
	raise SystemExit(main())
